### ISSUE TITLE
How to Read Mp3 file form SPIFFS and play on A2DP

### ISSUE THREAD

**Issue by Talhavaival1** [pschatzmann/arduino-audio-tools#1002]
### Problem Description

I have sucessfuly connected to my bluetooth speaker and tested its output using the generator a2dp sketch , how do I output an Audio file from spiffs to speaker.

### Device Description

ESP32cam

### Sketch

```cpp
no code
```

### What is your development environment

arduino

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by Talhavaival1** [comment]
well update , It seems I was download the wrong version , as I didnt get the release file version , but now even the sine test sketch is not working and I cant connect to my bluetooth speaker anymore.

**Comment by pschatzmann** [comment]
Check the issues and discussions of A2DP Project to resolve reconnect issues.

There are multiple examples that demonstrate how to play files to A2DP. 
I suggest to have a look at the player documentation...

**Comment by Talhavaival1** [comment]
But none of the example show how to play audio files from SPIFFS

**Comment by pschatzmann** [comment]
But in the end this does not matter: the mechanism is the same independently on what file system you use

**Comment by Talhavaival1** [comment]
Can you mention the example where it is done , Also I have made a sketch where I am reading mp3 from Spiffs but it says , no data to read to read Audioplayer 185 .

**Comment by pschatzmann** [comment]
> Can you mention the example where it is done , Also I have made a sketch where I am reading mp3 from Spiffs but it says , no data to read to read Audioplayer 185 .

In the audio player examples. You can also find a link in the audioplayer wiki

**Comment by pschatzmann** [comment]
Your sketch will not work! https://github.com/pschatzmann/ESP32-A2DP/wiki/WIFI-and-A2DP-Coexistence
