### ISSUE TITLE
Cant make work the "base-i2s-a2dp.ino" sketch whit the inmp441

### ISSUE THREAD

**Issue by Jorge339** [pschatzmann/arduino-audio-tools#103]
In the I2s to A2DP sketch, in the .MD file it says they are using the INMP441 microphone, but in the comments on the sketch it says they are using the  ADS1015 microphone, so I was trying to make work the sketch whit the INMP441 but was not able to do it, maybe some extra configuration is needed to make it work whit that microphone?

I was able to use the "base-i2s-serial" sketch which is made for the INMP441 microphone and i can see in the serial monitor that i have sound data, so the wiring in my tests are correct also using LITTLEFS i can record audio from the inmp441 to the flash memory and later extract that .wav audio and listen it on my PC, so that confirms that my mic is functional.

so the question is, what do i have to modifi in the  "base-i2s-a2dp.ino" code so it can work whit the INMP144 instead of the ADS1015 microphone?

**Comment by pschatzmann** [comment]
That's obviously a copy and past error in the sketch since the ADS1015 is not a microphone.
I havent't looked at the basic examples for a long time and I recommend to try to stream based example instead
