### ISSUE TITLE
Boosting the volume via VolumeStream is not possible anymore since commit " VolumeStream no processing when volume is 1.0"

### ISSUE THREAD

**Issue by crazy-weasel** [pschatzmann/arduino-audio-tools#1066]
### Problem Description

Hi!

applyVolume won't be called for any value higher then 1, regardless of the volumeConfig.allow_boost value

https://github.com/pschatzmann/arduino-audio-tools/commit/860572c79a33ce81609be76e7ade8d14b56c288c

Thank you for your time :)

### Device Description

any, as it is device independent code

### Sketch

```cpp
not provided as bug is trivial
```

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
The correction has been committed
