### ISSUE TITLE
Volume Control and Panning Issue

### ISSUE THREAD

**Issue by willdatrill2007** [pschatzmann/arduino-audio-tools#1070]
### Problem Description

When I try to control volume on each channel using the VolumeStream class, "volume.setVolume(1.0, 0);" and  "volume.setVolume(0.5, 1);", no audible change is heard. Volume will only change on both channels at the same time if I don't specify the channel number i.e. " "volume.setVolume(1.0);"

### Device Description

ESP32-S3 Devkit 1 with PCM1808 ADC Module and PCM5102 DAC Module

### Sketch

```cpp
#include "AudioTools.h"

AudioInfo info(96000, 2, 32);
I2SStream in;
I2SStream out; 
VolumeStream volume(out);
StreamCopy copier(volume, in); // copies sound into i2s

void setup(void) {  

  Serial.begin(115200);
  
  //AudioLogger::instance().begin(Serial, AudioLogger::Info);
   
  // start I2S in
  Serial.println("starting I2S...");
  auto config_in = in.defaultConfig(RX_MODE);
  config_in.i2s_format = I2S_STD_FORMAT;
  config_in.is_master = true;
  config_in.auto_clear = true;
  config_in.use_apll = true;
  config_in.sample_rate = 96000;
  config_in.buffer_size = 1024;
  config_in.bits_per_sample = 32;
  config_in.channels = 2;
  config_in.port_no = 0;
  config_in.pin_bck = 37;
  config_in.pin_ws = 36;
  config_in.pin_data = 38;
  config_in.pin_mck = 0;
  config_in.fixed_mclk = 24576000;
  in.begin(config_in);

  // start I2S out
  auto config_out = out.defaultConfig(TX_MODE);
  config_out.i2s_format = I2S_STD_FORMAT;
  config_out.is_master = true;
  config_out.sample_rate = 96000;
  config_out.buffer_size = 1024;
  config_out.bits_per_sample = 32;
  config_out.channels = 2;
  config_out.port_no = 1;
  config_out.pin_bck = 16;
  config_out.pin_ws = 15;
  config_out.pin_data = 17;
  out.begin(config_out);
  volume.begin(config_out);

  volume.setVolume(1.0, 0); 
  volume.setVolume(0.5, 1);

  Serial.println("I2S started...");

}

void loop() {
  copier.copy();  // Arduino loop - copy sound to out
  
}
```

### What is your development environment

Arduino

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by willdatrill2007** [comment]
I tried it with PREFER_FIXEDPOINT enabled but same result.

**Comment by willdatrill2007** [comment]
Ok, great. Thank you for your assistance. 

So far, it has been working very good. I had an issue with choppy audio when audiologger was sent to the serial out. I disabled it and then it worked flawlessly.

On the PCM1808, I set FMY, MD0 and MD1 to GND. The pin connection for both modules is described in the code posted above.

**Comment by pschatzmann** [comment]
Log level info is only activated to test so that the user can double check if the sketch is doing anything at all. 
For any productive use, I recommend to set it to Warning (which is the default setting).

I am usually testing with an AudioKit board, but there the max sample rate is limited to 48000

**Comment by willdatrill2007** [comment]
Noted!!! Will set it to "Warning" going forth.

Thank you so much. The independent volume control is working now. 

Another question, If I want to invert audio on one channel, can I use a negative value for the volume control? I am trying to implement Mid/Side Encoding and decoding in my project to add and subtract from audio channels.

**Comment by pschatzmann** [comment]
Oh, I just added a check to prevent negative values, because I thought that this does not make any sense.
I suggest that you comment out this check and let me know if negative values would actually work for this after doing some tests

**Comment by willdatrill2007** [comment]
I just tried it and negative values don't invert the audio signal. Is there any way to decode or encode mid/side signals from a stereo pair?
