### ISSUE TITLE
Cannot Install Audio Tools in Arduino IDE

### ISSUE THREAD

**Issue by robert1x2** [pschatzmann/arduino-audio-tools#1093]
### Problem Description

<img width="386" alt="image" src="https://github.com/pschatzmann/arduino-audio-tools/assets/24563846/27ec501d-d094-4060-9f0e-3cdfd6608ae9">

### Other Steps to Reproduce

Error appears every time when downloading zip file form github, and importing in Arduino IDE when using Sketch -> Include Library -> Add .ZIP Library ... function

### What is your development environment

Running on Windows 11
Arduino IDE 2.2.1

### Workarounds

Install manually in Arduino libraries folder

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
I don't see any issue with my library.
I guess you have some installation problem with arduino or just not enough memory
