### ISSUE TITLE
Update  base-file_mp3-a2dp.ino

### ISSUE THREAD

**Issue by Dweaver309** [pschatzmann/arduino-audio-tools#11]
Fantastic library I would suggest one change to  "base-file_mp3-a2dp.ino".
I was not able to connect to my M5Stack Core 2 SD drive. I added this code 

Added code:
int SPI_MOSI = 23;
int SPI_MISO = 38;
int SPI_SCK = 18;

SPI.begin(SPI_SCK, SPI_MISO, SPI_MOSI);

Just above the code below:

// Open MP3 file and play it
  SD.begin(sd_ss_pin); 

Thanks for a great project!

**Comment by pschatzmann** [comment]
I have updated the readme
