### ISSUE TITLE
HTML Not found

### ISSUE THREAD

**Issue by Ephesian** [pschatzmann/arduino-audio-tools#1104]
### Problem Description

Helo
I dont think this works, pops an error in browser, and I dont see html folder in the source.

https://pschatzmann.github.io/arduino-audio-tools/html/modules.html

### Device Description

General

### Sketch

```cpp
Browser HTML
```

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
I don't quite understand: where did you get this link from ?
All the documented links in the Readme of this project are working w/o any issues...

**Comment by Ephesian** [comment]
Hello 
in the doc folder->ext->index.html  .  Hope this make sense

**Comment by pschatzmann** [comment]
Just use the online documentation.
If you want to use it locally, you need to generate it with doxygen yourself
