### ISSUE TITLE
Platformio integration

### ISSUE THREAD

**Issue by githubgoucho** [pschatzmann/arduino-audio-tools#1128]
### Problem Description

Hi,
I tried to  git clone https://github.com/pschatzmann/arduino-audio-tools into the lib folder and got this output:

git clone https://github.com/pschatzmann/arduino-audio-tools
Cloning into 'arduino-audio-tools'...
remote: Enumerating objects: 82986, done.
remote: Counting objects: 100% (4011/4011), done.
remote: Compressing objects: 100% (745/745), done.
error: 1115 bytes of body are still expected MiB | 514.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

any idea what went wrong?

### Device Description

esp32s3

### Sketch

```cpp
git clone
```

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
This is definitely not the right place to file git or github issues 

See https://github.com/orgs/community/discussions/48568
