### ISSUE TITLE
player-url_icy-i2s.ino' example doesn't print song titles?

### ISSUE THREAD

**Issue by perlix** [pschatzmann/arduino-audio-tools#134]
[Environment: Arduino IDE 1.8.19 + arduino-esp32 1.0.6]

Running the 'player-url_icy-i2s.ino' example, I noticed that the printMetaData() function only prints info from the station's initial 
http response header (Genre and Name). Song title info between two mp3 data blocks will not print, even if the AudioLogger shows that there's "StreamTitle=..." metadata.

The problem seems to be in the substring mechanism of the processMetaData() function inside MetaDataICY.h.
Code inside this _if_ section 
```
if (start>=0 && end>start){
  metaData[end]=0;
  callback(Title, (const char*)metaData+start+1, end-start);
} 
```
appears not be executed because the value of both _start_ and _end_ is -1.

After putting the command 
`callback(Title, (const char*)metaData, len);`
outside that _if_ section, I get the expected output:

```
[W] HttpHeader.h : 230 - Waiting for data...
[W] HttpRequest.h : 145 - no CONTENT_LENGTH found in reply
==> Genre: Rock
==> Name: DylanRadio.com
==> Title: StreamTitle='Tribute To Bob by Andy';StreamUrl='http://www.myspace.com/anbamusic';
==> Title: StreamTitle='The Wicked Messenger by Bob Dylan';StreamUrl='http://www.dylanradio.com';
==> Title: StreamTitle='Frankie and Albert by Bob Dylan';StreamUrl='http://www.bobdylan.com';
```
Wonder if it's a bug or a version problem of my environment.

BTW: this library is fantastic!

**Comment by pschatzmann** [comment]
The bug has been corrected and I committed the correction to github
