### ISSUE TITLE
unexpected results for a2dp_source.is_connected() 

### ISSUE THREAD

**Issue by jcwrls** [pschatzmann/arduino-audio-tools#1353]
### Problem Description

The AudioTools library has been used to build reliable one-way A2DP connections with our unit as a source.

Within, the BluetoothA2DPSource method 'set_on_connection_state_changed' is used to register the call back 'connection_state_changed', as follows:
 
a2dp_source.set_on_connection_state_changed(connection_state_changed);
 
This is successful and the function  'connection_state_changed' appears to get called every time there is a change in connection state. 
 
However, the two different attempts below to test whether the A2DP is connected produce contradictory results:-
"connected = (state == ESP_A2D_CONNECTION_STATE_CONNECTED);"
and
"connected2 = a2dp_source.is_connected();"

Sketch example included below.

The 'is_connected' method produces unexpected result(s).  Is there something wrong in its usage?

### Device Description

ESP32-WROOM-32E

### Sketch

```cpp
void connection_state_changed(esp_a2d_connection_state_t state, void *ptr){

  Serial.printf("State is now...%s \n", a2dp_source.to_str(state));

  connected = (state == ESP_A2D_CONNECTION_STATE_CONNECTED);
  Serial.printf("connected is: %s \n", connected ? "true" : "false");

  connected2 = a2dp_source.is_connected();
  Serial.printf("connected2 is: %s \n", connected2 ? "true" : "false");

  if (connected != connected2) {
    Serial.printf("Why do these two not agree???\n");
  }
}
```

### Other Steps to Reproduce

Also, when used elsewhere in the code, the 'is_connected’ method seems to be the cause of exceptions / re-boots.  

### What is your development environment

Arduino IDE

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
So far I concentrated on the connection state handling for the audio sink and the implementatioin for the source was quite messy.
I cleaned up the logic a bit and committed the correction. 

I hope this will resolve your issue...
