### ISSUE TITLE
Compile error in MetaDataICY.h

### ISSUE THREAD

**Issue by mikemccauley** [pschatzmann/arduino-audio-tools#137]
Line 210:                
LOGI("%s: %d", metaData);
causes compile error:
/usr/local/projects/arduino/libraries/arduino-audio-tools-main/src/AudioMetaData/MetaDataICY.h:210:17: note: in expansion of macro 'LOGI'
                 LOGI("%s: %d", metaData);

Line 210 should be:
                LOGI("%s: %d", metaData, len);

**Comment by pschatzmann** [comment]
The correction has been committed. Thanks for your feed-back
