### ISSUE TITLE
Feature Request: Volume Control for separate channels

### ISSUE THREAD

**Issue by mageeagle** [pschatzmann/arduino-audio-tools#139]
I wanted to make a panner out of my ESP32 board. 
Right now there is the volume control feature which controls the volume of audio streams.
https://github.com/pschatzmann/arduino-audio-tools/wiki/Volume-Control

Though it controls the amplitude of both channels of a stereo output stream together with one value.
Wonder if it's possible to control the amplitude separately for each channel? So that it works like a panner for an audio stream?

**Comment by pschatzmann** [comment]
I extended the [VolumeControl](https://pschatzmann.github.io/arduino-audio-tools/html/classaudio__tools_1_1_volume_stream.html). Can you help me to test it ?

**Comment by mageeagle** [comment]
It works perfectly! Thanks!
