### ISSUE TITLE
example streams-audiokit-webserver_wav no sound with AI audiokit

### ISSUE THREAD

**Issue by franki29** [pschatzmann/arduino-audio-tools#1442]
### Problem Description

example streams-audiokit-webserver_wav no sound with AI audiokit.
Example streams-audiokit-audiokit is working

When I change auto config = kit.defaultConfig(RX_MODE); to auto config = kit.defaultConfig(RXTX_MODE); it is working.
Not sure if this is OK

Br. Frank

### Device Description

Audiokit v2.2

### Sketch

```cpp
https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-audiokit/streams-audiokit-webserver_wav/streams-audiokit-webserver_wav.ino
```

### What is your development environment

Arduino

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
The I2S pins were not determined correctly...
