### ISSUE TITLE
NoiseGenerator i2s amplitude error

### ISSUE THREAD

**Issue by timmcarson** [pschatzmann/arduino-audio-tools#145]
Trying to use to NoiseGenerator with the i2s output with scale of 32000 but only got a 50mV output

in the main file:
`NoiseGenerator<sound_t> wNoise(32000); 
GeneratedSoundStream<sound_t> sound(wNoise);
wNoise.begin();`

Changing the NoiseGenerator class return value fixed the issue for me and gives full pk-pk voltage now.  Not sure if there is a better way to do it. but this is what I did.

From:
`return  ((rand() % (static_cast<T>(2 * scale)) - scale));`

To:
`return  (random(-scale,(scale+1)));`

**Comment by pschatzmann** [comment]
The correction has been committed
