### ISSUE TITLE
How to downmix to mono

### ISSUE THREAD

**Issue by hasaranga** [pschatzmann/arduino-audio-tools#1490]
### Problem Description

Hi,
I'm using sample project "player-url_icy_i2s" to listen online radio. Since I'm using a single speaker, I would like to downmix the audio to mono. How to modify that example to do that? Please help!
Thanks!

### Device Description

ESP32

### Sketch

```cpp
player-url_icy_i2s
```

### What is your development environment

Arduino

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/arduino-audio-tools/wiki/Converting-the-Data-Format
