### ISSUE TITLE
WM8960 audio board Vcc 

### ISSUE THREAD

**Issue by vorosj** [pschatzmann/arduino-audio-tools#1581]
### Problem Description

https://github.com/pschatzmann/arduino-audio-tools/wiki/Audio-Boards
The Vcc in the pinout of the WM8960 Audio Board is 5V (probably kills it), the correct value is 3.3V.
Datasheet: https://files.waveshare.com/upload/5/58/WM8960_Audio_Board_User_Manual_en.pdf

### Device Description

WM8960 Audio Board

### Sketch

```cpp
...
```

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
Thanks, i have updated the document.
