### ISSUE TITLE
Wrong folder structure

### ISSUE THREAD

**Issue by FinianLandes** [pschatzmann/arduino-audio-tools#1588]
### Problem Description

There seems to be issues with your folder structure so the code wont compile
eg. a header in audio tools including anotherone with #include "AudioTools/other_header.h" instead of just #include "other_header.h" as we are already inside of audio tools
The same is true for files outside of a directory there we need to include #include "AudioBasic/some_header.h" with the #include "..\AudioBasic/some_header.h" when in another directory which is deeper inside 

### Device Description

ESP32Wroom

### Sketch

```cpp
Compiling just the library with an instance of the main class inside of the arduino ide should be enough
```

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
I am sorry but your error report does not make any sense at all.
- There is no file other_header.h
- There is no need to import any class for the standard functionality: just importing Arduino.h should be good enough.

You would just need to use import for [optional functionality](https://github.com/pschatzmann/arduino-audio-tools/wiki/Optional-Libraries)
