### ISSUE TITLE
Guru error after esp32 update ver 3

### ISSUE THREAD

**Issue by stiebel** [pschatzmann/arduino-audio-tools#1589]
### Problem Description

I had an esp32 update last week.
Just after that all your scripts permanently reboot with guru error.
the standard i2s.h (e.g. atomic14) works fine

### Device Description

esp32wroom

### Sketch

```cpp
your sketches
```

### Other Steps to Reproduce

let install esp32 v3

### What is your development environment

arduino ubuntu linux

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
Sorry but you don't provide any information that would enable me to help you!
- You don't give me any information about your sketch
- I have no clue what core version you are using
- You don't provde any error messages
