### ISSUE TITLE
fatal error: WiFi.h: No such file or directory

### ISSUE THREAD

**Issue by eneuberg** [pschatzmann/arduino-audio-tools#1670]
### Problem Description

When i try to compile, I am getting the error that i cant import Wifi.h inside of the library, specifically inside of URLStream.h. I can import it normally in my sketch. I have tried importing it before I import AudioTools.h but it doesnt help

Compiling .pio\build\esp32dev\lib473\ESP32-A2DP-main\BluetoothA2DPSinkQueued.cpp.o
In file included from lib/arduino-audio-tools/src/AudioHttp/AudioHttp.h:8,
                 from lib/arduino-audio-tools/src/AudioTools.h:96,
                 from lib/ESP32-A2DP-main/src/BluetoothA2DPOutput.h:13,
                 from lib/ESP32-A2DP-main/src/BluetoothA2DPOutput.cpp:1:
lib/arduino-audio-tools/src/AudioHttp/URLStream.h:8:10: fatal error: WiFi.h: No such file or directory

### Device Description

ESP32 Wroom

### Sketch

```cpp
#include <Arduino.h>  // Include the Arduino library
//#include "WifiManager.h"
//#include <WiFi.h>
//#include "MQTTHandler.h"
#include "AudioTools.h"
#include "AudioDownloader.h"
#include "AudioLibs/A2DPStream.h"
#include "AudioCodecs/CodecFLAC.h"

const String url = URL;

//WiFiManager wifiManager;

AudioInfo info16(44100, 2, 16);
AudioInfo info8(11025, 1, 8);
FormatConverterStream conv;
FLACDecoder flacDecoder;
A2DPStream out;                                           
StreamCopy converterCopier(out, conv); // copy in to out

...
```

### What is your development environment

PlatformIO

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
This is a PlatformIO issue: just google to topic to find the solution
