### ISSUE TITLE
Not compatable with ESP32 core version 3.0.4

### ISSUE THREAD

**Issue by MaxCordell** [pschatzmann/arduino-audio-tools#1686]
### Problem Description

The library will not compile for ESP32 boards if version 3.0.4 of the ESP32 boards library is installed. Downgrading to version 2.0.16 fixes the problem.

![image](https://github.com/user-attachments/assets/2e20421b-6004-4df7-bc25-b016258fa12d)

### Device Description

XIAO ESP32C3

### Sketch

```cpp
#include "AudioTools.h"
```

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
My mistake, I tested on the wrong version.

The [correction has been committed](https://github.com/pschatzmann/arduino-audio-tools/commit/53414e7294fe29617c0e02965a5df71e03598a44)
