### ISSUE TITLE
Why is DSP code expanded ?

### ISSUE THREAD

**Issue by sletz** [pschatzmann/arduino-audio-tools#173]
The code https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-audiokit/streams-faust-i2s/Noise.dsp and https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-audiokit/streams-generator-faust-i2s/volume.dsp is "expanded" ? Any reason not to keep the original "non expanded" Faust DSP code?

**Comment by pschatzmann** [comment]
I didn't have the time to test what's working and what not. 
Just notice that in the current implementation the input and output buffer are the same because I did not want to wast any memory. Though I plan to have an option to change this

**Comment by sletz** [comment]
But how what the expanded DSP code generated ? (by "expanded" I mean  code with `ID_325` kind of identifiers ?)

**Comment by pschatzmann** [comment]
I am not aware that I did anything special. I just used FaustLive and exported from there..

**Comment by sletz** [comment]
Then you could possibly just keep the original DSP source code?

**Comment by pschatzmann** [comment]
Well, in Arduino there is no mechanism to automatically generate the the CPP code from the DSP code.
