### ISSUE TITLE
Broken link in wiki (Performance > i2s config)

### ISSUE THREAD

**Issue by iuliux** [pschatzmann/arduino-audio-tools#1736]
### Problem Description

In [Performance](https://github.com/pschatzmann/arduino-audio-tools/wiki/Performance) Wiki, Overview, the link [i2s config](https://pschatzmann.github.io/arduino-audio-tools/classaudio__tools_1_1_i2_s_config.html) leads to a 404.

### Device Description

NA

### Sketch

```cpp
NA
```

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
Please note that this is platform and for the ESP32 also version dependent! So double check the class documentation!)
I added the example for the current ESP32.
