### ISSUE TITLE
MemoryOutput filling buffer faster than expected

### ISSUE THREAD

**Issue by kristiamo** [pschatzmann/arduino-audio-tools#1740]
### Problem Description

I'm trying to get MemoryOutput to work, however it's only getting 200-500ms into recording before reporting the buffer is too small.  Strangely, this behaviour changes based on which LogLevel I use.  If WARNING, it loops very quickly for 200-500ms, then gives errors and jumps big blocks of time.  If DEBUG, it loops slower consistent blocks, and never reports any buffer errors.

In the full project, I've added a VolumeStream alternating the volume every 100ms for visual reference.  I then transfer the byte array to my PC and import into Audacity. I've attached a picture (and logs) showing the different behaviour.  Both debug/warning play the correct tone. It sounds right.  However, the length of the recording and the volume intervals are different.  WARNING is very stretched out, and DEBUG is very compressed.  Neither with the correct 100ms intervals.  I can't understand it because they both have the right pitch.
[LogLevel_debug.txt](https://github.com/user-attachments/files/17355180/LogLevel_debug.txt)
[LogLevel_warning.txt](https://github.com/user-attachments/files/17355181/LogLevel_warning.txt)
![SineWave](https://github.com/user-attachments/assets/f8e84b67-c5ee-49cd-b8d6-92ec918a2b62)

### Device Description

ESP32-S3 N16R8

### Sketch

```cpp
#include "AudioTools.h"
AudioInfo infoStereo16(44100, 2, 16);

// INPUTS
SineWaveGenerator<int16_t> sineWave( pow(2, 16) * 0.9 / 2); // subclass of SoundGenerator with max amplitude 90% of int res
GeneratedSoundStream<int16_t> sineSound(sineWave);  // Stream generated from sine wave

// OUTPUTS
uint8_t memRaw[204800] = {}; // 200kb, enough for 1.15s @ 44.1khz-16bit-Stereo ?
MemoryOutput memOut(memRaw, 204800);

WAVEncoder encoder;
EncodedAudioOutput recordOut(&memOut, &encoder);
StreamCopy copier(recordOut, sineSound);

// recording vars
uint64_t timeout;
uint64_t recStartTime;
bool bRecord = false;


void setup() {
  Serial.begin(115200);
  delay(100);

  AudioLogger::instance().begin(Serial, AudioLogger::LogLevel::Debug);
  //AudioLogger::instance().begin(Serial, AudioLogger::LogLevel::Warning);

  sineWave.begin(infoStereo16, N_A4);
  recordOut.begin(infoStereo16);
  
  delay(1000);
  //START RECORD
  recStartTime = millis();
  timeout = recStartTime + 1000;
  bRecord = true;
}


void loop() {
  if (bRecord) {
    if (millis() < timeout) {
      Serial.printf("\r\nrecTime: %ldms  - RECORDING...\r\n", millis() - recStartTime);
      copier.copy();
    }
    else {
      bRecord = false;
      Serial.printf("\r\nrecTime: %ldms  - RECORDING END\r\n", millis() - recStartTime);
    }
  }
}
```

### What is your development environment

Arduino IDE

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
I think you are mixing up the time it takes to generate audio with the one it takes to play it back with the correct sampling rate!

If you want to change the volume at some defined times, you will need to check the MemoryOutput.size().
You could also run the recoring thru a Throttle to low down the recording speed.
