### ISSUE TITLE
additional URL player settings

### ISSUE THREAD

**Issue by podaen** [pschatzmann/arduino-audio-tools#176]
Phill,

I have a few addition question on top of url player I am working with. 

1) Do you have a tool to implement to the player to adjust those tones?
2) Is is possible to audio volume leveling soo all url-streams are less or most the same volume?

**Comment by podaen** [comment]
I mean low-mid-base tones

**Comment by pschatzmann** [comment]
You can try https://pschatzmann.github.io/arduino-audio-tools/html/classaudio__tools_1_1_equilizer3_bands.html
However it is not tested yet...
