### ISSUE TITLE
Adafruit_USBD_Audio not found, compile error

### ISSUE THREAD

**Issue by HenniePeters** [pschatzmann/arduino-audio-tools#1762]
### Problem Description

example sketch doesn't compile  
'Adafruit_USBD_Audio' does not name a type; did you mean 'Adafruit_USBH_CDC'?

libraries that are listed in the .ino are installed:  
#include "Adafruit_TinyUSB.h" // https://github.com/pschatzmann/Adafruit_TinyUSB_Arduino
#include "AudioTools.h"  // https://github.com/pschatzmann/arduino-audio-tools

### Device Description

ESP32-WROOM-32

### Sketch

```cpp
examples/audio-tools/examples-communication/usb/microphone sketch with no alterations
```

### What is your development environment

Arduino 1.8.19

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
ESP32 is not supported (yet)
