### ISSUE TITLE
Adafruit_USBD_Audio non-functional. Missing in both libraries?

### ISSUE THREAD

**Issue by Synergyst** [pschatzmann/arduino-audio-tools#1770]
### Problem Description

I get the following error when trying to initialize `Adafruit_USBD_Audio`:
Compilation error: 'Adafruit_USBD_Audio' does not name a type; did you mean 'Adafruit_USBD_Video'?

```
root@d0006:~/Arduino/libraries# grep -r 'Adafruit_USBD_Audio' .
./audio-tools/examples/examples-communication/usb/microphone/microphone.ino:Adafruit_USBD_Audio usb;
root@d0006:~/Arduino/libraries#
root@d0006:~/Arduino/libraries# cat audio-tools/library.properties Adafruit_TinyUSB_Library/library.properties
name=audio-tools
version=0.9.9
author=Phil Schatzmann
maintainer=Phil Schatzmann
url=https://github.com/pschatzmann/arduino-audio-tools
...
truncated
...
name=Adafruit TinyUSB Library
version=3.4.0
author=Adafruit
maintainer=Adafruit <info@adafruit.com>
url=https://github.com/adafruit/Adafruit_TinyUSB_Arduino
root@d0006:~/Arduino/libraries#
```

I only found one reference of `Adafruit_USBD_Audio` using grep. I'm not sure if I did something wrong with the install, though I can't seem to find any other reference to it on Github either outside of microphone.ino. See: https://github.com/search?q=Adafruit_USBD_Audio&type=code

### Device Description

Raspberry Pi Pico RP2040 and Pico 2 RP2350

### Sketch

```cpp
#include <Adafruit_TinyUSB.h>
#include "AudioTools.h"  // https://github.com/pschatzmann/arduino-audio-tools
#define SAMPLE_RATE 16000
Adafruit_USBD_Audio usb_audio; // <<< ------ Compilation error: 'Adafruit_USBD_Audio' does not name a type; did you mean 'Adafruit_USBD_Video'?
```

### Other Steps to Reproduce

I noticed issue #1762 though they are using a different device.

### What is your development environment

Arduino IDE (v2.3.2)

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
Follow thee [instructions of the Wiki](https://github.com/pschatzmann/Adafruit_TinyUSB_Arduino/wiki)!
