### ISSUE TITLE
PDM-RX for esp32-c3

### ISSUE THREAD

**Issue by karloscampus** [pschatzmann/arduino-audio-tools#1810]
### Problem Description

Recieving compile error then compiling on esp32-c3 an example:

In file included from /Users/karoliskleiza/Documents/Arduino/libraries/audio-tools/src/AudioTools/CoreAudio/AudioI2S/I2SStream.h:10,
                 from /Users/karoliskleiza/Documents/Arduino/libraries/audio-tools/src/AudioTools.h:81,
                 from /Users/karoliskleiza/development/private/game_counter_flutter/arduino/mp3_stream_test/mp3_stream_test.ino:13:
/Users/karoliskleiza/Documents/Arduino/libraries/audio-tools/src/AudioTools/CoreAudio/AudioI2S/I2SESP32V1.h:322:5: error: 'i2s_pdm_rx_slot_config_t' does not name a type; did you mean 'i2s_pdm_tx_slot_config_t'?
  322 |     i2s_pdm_rx_slot_config_t getRxSlotConfig(I2SConfigESP32V1 &cfg) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
      |     i2s_pdm_tx_slot_config_t
/Users/karoliskleiza/Documents/Arduino/libraries/audio-tools/src/AudioTools/CoreAudio/AudioI2S/I2SESP32V1.h:338:5: error: 'i2s_pdm_rx_clk_config_t' does not name a type; did you mean 'i2s_pdm_tx_clk_config_t'?
  338 |     i2s_pdm_rx_clk_config_t getRxClockConfig(I2SConfigESP32V1 &cfg) {
      |     ^~~~~~~~~~~~~~~~~~~~~~~
      |     i2s_pdm_tx_clk_config_t
/Users/karoliskleiza/Documents/Arduino/libraries/audio-tools/src/AudioTools/CoreAudio/AudioI2S/I2SESP32V1.h: In member function 'bool audio_tools::I2SDriverESP32V1::DriverPDM::startRX(audio_tools::I2SConfigESP32V1&, i2s_channel_obj_t*&, int)':
/Users/karoliskleiza/Documents/Arduino/libraries/audio-tools/src/AudioTools/CoreAudio/AudioI2S/I2SESP32V1.h:369:7: error: 'i2s_pdm_rx_config_t' was not declared in this scope; did you mean 'i2s_pdm_tx_config_t'?
  369 |       i2s_pdm_rx_config_t pdm_rx_cfg = {
      |       ^~~~~~~~~~~~~~~~~~~
      |       i2s_pdm_tx_config_t
/Users/karoliskleiza/Documents/Arduino/libraries/audio-tools/src/AudioTools/CoreAudio/AudioI2S/I2SESP32V1.h:383:50: error: 'pdm_rx_cfg' was not declared in this scope
  383 |       if (i2s_channel_init_pdm_rx_mode(rx_chan, &pdm_rx_cfg) != ESP_OK) {
      |                                                  ^~~~~~~~~~
/Users/karoliskleiza/Documents/Arduino/libraries/audio-tools/src/AudioTools/CoreAudio/AudioI2S/I2SESP32V1.h:383:11: error: 'i2s_channel_init_pdm_rx_mode' was not declared in this scope; did you mean 'i2s_channel_init_pdm_tx_mode'?
  383 |       if (i2s_channel_init_pdm_rx_mode(rx_chan, &pdm_rx_cfg) != ESP_OK) {
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |           i2s_channel_init_pdm_tx_mode

### Device Description

Waveshare Esp32-c3 mini 

### Sketch

```cpp
/**
 * @file streams-url_mp3-i2s.ino
 * @author Phil Schatzmann
 * @brief decode MP3 stream from url and output it on I2S
 * @version 0.1
 * @date 2021-96-25
 * 
 * @copyright Copyright (c) 2021
 */

// install https://github.com/pschatzmann/arduino-libhelix.git

#include "AudioTools.h"
#include "AudioTools/AudioCodecs/CodecMP3Helix.h"


URLStream url("Karlos WIFI","XXXXXXXXX");
I2SStream i2s; // final output of decoded stream
EncodedAudioStream dec(&i2s, new MP3DecoderHelix()); // Decoding stream
StreamCopy copier(dec, url); // copy url to decoder


void setup(){
  Serial.begin(115200);
  AudioToolsLogger.begin(Serial, AudioToolsLogLevel::Info);  

  // setup i2s
  auto config = i2s.defaultConfig(TX_MODE);
  // you could define e.g your pins and change other settings
  //config.pin_ws = 10;
  //config.pin_bck = 11;
  //config.pin_data = 12;
  //config.mode = I2S_STD_FORMAT;
  i2s.begin(config);

  // setup I2S based on sampling rate provided by decoder
  dec.begin();

// mp3 radio
  url.begin("http://f131.rndfnk.com/ard/rb/bremenvier/live/mp3/64/stream.mp3?cid=01FC1W6QK48EBYZ3RJW932FC1E&sid=2pJCIINlcGDxTwqIYejVnAejUff&token=wJnXUuJjDwzxfsp_e-JMnGAHggJRe8PbnYxMhg_UQK0&tvf=uA5R-DYQCxhmMTMxLnJuZGZuay5jb20","audio/mp3");

}

void loop(){
  copier.copy();
}
```

### What is your development environment

Arduino IDE

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
I deactivated PDM RX support for ESP32 versions that do not support this
