### ISSUE TITLE
error: 'WiFiClient' does not name a type; did you mean 'Client'?

### ISSUE THREAD

**Issue by KMTsvetanov** [pschatzmann/arduino-audio-tools#1820]
### Problem Description

How to disable all unnecessary things like the WIFI?

I'm using esp32-h2 that doesn't have WIFI.
I wish to make a Sine Wave to test my DAC PCM5102 
No more, no less. 
Why it's so hard just to try it...

![image](https://github.com/user-attachments/assets/0e3c7020-5bea-4efa-a991-f69007aedc90)

![image](https://github.com/user-attachments/assets/85ffb7f4-1990-4448-933b-21e272b266ca)

### Device Description

esp32-h2 , I2S PCM5102 DAC Decoder

### Sketch

```cpp

void DAC_setup() {
  auto cfg = i2s.defaultConfig(TX_MODE);
  cfg.sample_rate = 44100;   // Set the sample rate to 44.1 kHz
  cfg.bits_per_sample = 16;  // Set bits per sample to 16
  cfg.channels = 2;          // Stereo output

  // Define the I2S pins
  cfg.pin_bck = 8;        // Bit Clock (BCK)
  cfg.pin_ws = 25;        // Word Select (L/R clock) (LCK)
  cfg.pin_data = 12;      // Data out (DIN)

  i2s.begin(cfg);  // Start the I2S
}
void setup() {
  Serial.begin(115200);
  while (!Serial) delay(1000);

  Serial.println("Hello from setup!");
}

void loop() {
}
```

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
Oh, I did not realize that thre is an esp32 that does not support any wifi!
I committed a correction...
