### ISSUE TITLE
ESP32 Can't compile no memory

### ISSUE THREAD

**Issue by SSkrzypik** [pschatzmann/arduino-audio-tools#1823]
### Problem Description

Jedyne, co musi zrobić, to napisać 
#include „AudioTools.h”
nie ma wystarczająco dużo miejsca na kompilacje. Kompilacja samego szkicu zajmuje dużo czasu.
Czy są jakieś metody na zmniejszenie rozmiaru biblioteki?

### Device Description

DOIT ESP32 DEVKIT V1

### Sketch

```cpp
#include "AudioTools.h"
#include "BluetoothA2DPSink.h"

I2SStream out;
BluetoothA2DPSink a2dp_sink(out);

void setup() {
  a2dp_sink.start("MyMusic");  
}


void loop() {
  delay(1000); // do nothing
}
```

### What is your development environment

Arduino IDE

### I have checked existing issues, discussions and online documentation

- [ ] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
Read the FAQ of the A2DP library!
