### ISSUE TITLE
How to apply effects to the sound data received from bluetooth

### ISSUE THREAD

**Issue by zagebd666** [pschatzmann/arduino-audio-tools#1824]
### Problem Description

I try to apply the effects (fuzz, distrotion, ...) to the I2SStream I receive from bluetooth. However, this two effects sound the same, and they both sound terrible ,for the bluetooth, I use your library A2DP.  

### Device Description

ESP32-Wroom-32, PCM5102

### Sketch

```cpp
#include "AudioTools.h"
#include "BluetoothA2DPSink.h"

I2SStream out;
BluetoothA2DPSink a2dp_sink(out);
AudioEffectStream effects(out);

// Effects control input
int16_t clipThreashold = 4990;
float fuzzEffectValue = 50;
int16_t fuzzMaxValue = 0;

// Effects
Distortion distortion(clipThreashold);
Fuzz fuzz(fuzzEffectValue);

void setup() {
    Serial.begin(115200);
    AudioToolsLogger.begin(Serial, AudioToolsLogLevel::Warning);
    //effects.addEffect(distortion);
    effects.addEffect(fuzz);
    a2dp_sink.start("MyMusic");
}

void loop() {
}
```

### What is your development environment

Arduino

### I have checked existing issues, discussions and online documentation

- [X] I confirm I have checked existing issues, discussions and online documentation

**Comment by pschatzmann** [comment]
As described in the Readme: Please open issues only for bug!
In your sketch you don't use effects anywhere...
