### ISSUE TITLE
Trying the measuring stream example

### ISSUE THREAD

**Issue by podaen** [pschatzmann/arduino-audio-tools#183]
[communication example](https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-communication/communication-ip-receive_measure)

I want to try it, but I can't find MeasuringStream out;

Thanks

**Comment by pschatzmann** [comment]
Just wrap your final input or output in this class and use it instead. Example: https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-communication/communication-ip-send/communication-ip-send.ino
ps. The log level needs to be on info to see the result in the log.

**Comment by podaen** [comment]
it is not for measuring an http link?

**Comment by pschatzmann** [comment]
Obviously you did not process any data yet, since the log states that it's waiting for data.
If you want to look at the data you can use a HexDumpStream as output.

**Comment by podaen** [comment]
yep, see now some data

**Comment by podaen** [comment]
Now, how can I found the beginning of the frame?

**Comment by podaen** [comment]
Soo, I was right,

for this link

url.begin("http://22183.live.streamtheworld.com/JOE.mp3", "audio/mp3");

the input stops

**Comment by podaen** [comment]
Now I am going to config it and see if data still coming in. Seems a good strategie.

**Comment by podaen** [comment]
what could I do to change some settings of the input audio?

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/arduino-audio-tools/wiki/Performance

**Comment by podaen** [comment]
This maybe also important...

>   long rssi = WiFi.RSSI();
>   Serial.print("Signal strength (RSSI):");
>   Serial.print(rssi);
>   Serial.println(" dBm");

**Comment by pschatzmann** [comment]
I think the measuring stream question has been answered. 
In order to avoid any confusion I am closing this issue...
