### ISSUE TITLE
ESP32: Using internal DAC and ADC (with DMA) simultaneously

### ISSUE THREAD

**Issue by proteus74** [pschatzmann/arduino-audio-tools#196]
Hi Phil,
thank you, for your amazing work!

Is it possible to use the internal DAC and ADC of the ESP32 together at the same time with DMA?
I think your library doesn't support it right now. Am I right?

**Comment by pschatzmann** [comment]
I am not sure about the limitations of the ESP32 but you would need to assign the input and output to a different port_no.

**Comment by proteus74** [comment]
Thanks for your fast reply.
I'd tried it, but the **i2s_driver_install** will fail, saying "Internal DAC/ADC can only be used on **I2S_NUM_0**"

**Comment by pschatzmann** [comment]
OK, then the ESP32 does not support this...
