### ISSUE TITLE
Simultaneous tasks (BT Transmitting/Receiving + Recording)

### ISSUE THREAD

**Issue by rmond18** [pschatzmann/arduino-audio-tools#2]
Hi, thank you very much for this amazing library!

I'm planning to use the [base-i2s-a2dp code](https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples-basic-api/base-i2s-a2dp/base-i2s-a2dp.ino) for my project which also requires a recording feature. I would like to ask if it is feasible to add a function at the said base code to record for a certain time that will be saved as a WAV file to an SD card (triggered by push button) while transmitting data through Bluetooth at the same time? Is this do-able? Do I need to use the 2 cores of ESP32 for this (freeRTOS)? 

Thank you very much!
Warm regards,
Rmond

**Comment by rmond18** [comment]
I'm also currently planning to save the data received by the BT sink to an SD card as WAV file.

In this [discussion](https://github.com/pschatzmann/ESP32-A2DP/issues/31#issuecomment-864155736):
> // In the setup function:
> a2dp_sink.set_stream_reader(read_data_stream);
> 
> // Then somewhere in your sketch:
> void read_data_stream(const uint8_t *data, uint32_t length)
> {
> // Do something with the data packet
> }
> In the a2dp_sink.set_stream_reader() method you can provide an optional parameter that defines if you want the output to I2S to be active or deactive - So you can use this method to e.g. to switch off I2S just by calling a2dp_sink.set_stream_reader(read_data_stream, false)

In the "// Do something with the data packet" is where we can put the [WAVEncoder](https://github.com/pschatzmann/arduino-audio-tools/blob/main/src/CodecWAV.h)? How can the data be also processed by a lowpass filter before saving as wav file?

**Comment by pschatzmann** [comment]
Take a look at https://github.com/pschatzmann/arduino-audio-tools/blob/019940f1a94c11678e88138fe358100ce231a312/src/AudioWAVServer.h where I am doing something similar

If you want to process the data you can add a filter to the Copier.copy(filter) function.
