### ISSUE TITLE
Installation on PlatformIO

### ISSUE THREAD

**Issue by podaen** [pschatzmann/arduino-audio-tools#201]
Can't find The library from PIO Home -> Libraries

![2022-05-09_085804](https://user-images.githubusercontent.com/63886347/167356765-dede5c7f-8d44-4ccb-9254-e4d89c82715d.jpg)

**Comment by pschatzmann** [comment]
Which library. I have the impression that you did not read the Wiki: https://github.com/pschatzmann/arduino-audio-tools/wiki/Working-with-PlatformIO

**Comment by podaen** [comment]
I did get the msg that the library was not registered yet in the platformIO. That why I am telling you. It's very easy to install like that. I missed it in the readme, but now I see its there and I was looking for IDE title with in it Arduino, PlatformIO... Maybe it is because I'm really bizzy to get all the setting right for PlatformIO.
