### ISSUE TITLE
ADC- A2DP problems

### ISSUE THREAD

**Issue by mweetman2** [pschatzmann/arduino-audio-tools#205]
Hi
Firstly thanks for the great code with simple examples.
However, I am having problems with ADC-A2DP.
There seem to be 2 examples in your code:-
The base-adc-a2dp using a callback for the adc data.
The sandbox streams-adc-a2dp using stream copy to provide the A2DP data..
I am having issues with both using esp32doit-devkit-v1 under Platformio running on Windows.
The base-adc-a2dp callback only seems to be called once. The callbacks stop after the initial call. I haven't been able to trace the issue any further as yet.
The streams-adc-a2dp does produce audio at the Bluetooth sink, but the pitch is low, & the output glitches. This appears to be down to the ADC stream. Replacing the ADC with a Sine generator works fine. 
Can you give me any clues to investigate further? 
Thanks for any assistance.

**Comment by mweetman2** [comment]
Hi

Thanks for the tip on the Arduino version. This fixed the issue.

It’s working quite well now, but I begin to hear some clicks after a period of operation.  Resetting the ESP, or reconnecting the BT speaker makes the clicks go away, but they always return after about 30 seconds. They are quite low level on your example code (streams-adc-a2dp.ino), however, I have to boost the audio signal in my application which makes them more audible.

I am not sure who is the master clock is a BT system, but assume it’s the source, so the sink should adapt to the datarate?

I have changed the DC offset of the incoming audio, but this has no effect.

It sounds like a buffer over/under run, but I would need a deeper understanding or your code to work this out – if indeed it is a buffering issue.

 

Are you aware of any such problem? 

 

Regards

Martin Weetman

 

Phone +44 7798 903766

http://www.weetman.com

 

From: Martin Weetman ***@***.*** 
Sent: 12 May 2022 16:53
To: 'pschatzmann/arduino-audio-tools'; 'pschatzmann/arduino-audio-tools'
Cc: 'Author'
Subject: RE: [pschatzmann/arduino-audio-tools] ADC- A2DP problems (Issue #205)

 

Thanks so much for the extremely quick response. I was using version 2.0.2, so that could well be the problem.

I’m changing to 2.0.2 now, & hope that will fix the issue. Takes a while on Platformio 😉

Thanks again…

 

Regards

Martin Weetman

 

Phone +44 7798 903766

http://www.weetman.com

**Comment by pschatzmann** [comment]
Difficult to say: I suggest that you try to feed the bluetooth with a sine signal. If the clicks go away this would be an indication that the issue is with the I2S buffer.

**Comment by mweetman2** [comment]
Thanks for the quick response. 

I’ll give this a try....

 

Regards

Martin Weetman

 

Phone +44 7798 903766

**Comment by mweetman2** [comment]
Hi

Yes, a sine generated via math works fine with no glitches.

I checked the buffer coming from the AnalogAudioStream, & it is clean without glitches.

The problem appears to be under run of the A2DP buffer. 

If I increase the datarate of the Analog data the glitches go away:-

 

cfgRx.sample_rate = sample_rate + 330; // 350 was OK

 

I would need to look into the I2S & Bluetooth blocks in more detail to see how they are clocked. They should be synchronized.

Do you have any experience on this?

 

Thanks again for the great code…..

 

Regards

Martin Weetman

 

Phone +44 7798 903766

http://www.weetman.com

**Comment by pschatzmann** [comment]
To my knowledge A2DP is not really clocked, but synchronized via a buffer. If you also use an ESP32 to output the data it is the I2S output (clock) speed which is relevant.

**Comment by pschatzmann** [comment]
Closed due to inactivity

**Comment by mweetman2** [comment]
Thanks so much for the extremely quick response. I was using version 2.0.2, so that could well be the problem.

I’m changing to 2.0.2 now, & hope that will fix the issue. Takes a while on Platformio 😉

Thanks again…

 

Regards

Martin Weetman

 

Phone +44 7798 903766

http://www.weetman.com
