### ISSUE TITLE
compilation error on "communication-codec-espnow-send" example

### ISSUE THREAD

**Issue by Chirawat** [pschatzmann/arduino-audio-tools#210]
Got error message

`C:\Program Files (x86)\Arduino\libraries\arduino-audio-tools\src/AudioLibs/Communication.h:8:30: fatal error: esp_private/wifi.h: No such file or directory
`
Is there another library I need to install?

Thanks

**Comment by pschatzmann** [comment]
Interresting. If you go to Tools -> Board -> Board Manager and Select ESP32. What version are you using ?
The latest is 2.0.3...

**Comment by Chirawat** [comment]
> 

I use version 1.8.19. Now I install new Arduino (still same version) and download your updated library. It works.

Thank you!
