### ISSUE TITLE
Compilation error for streams-generator-a2dp

### ISSUE THREAD

**Issue by Denis-2021** [pschatzmann/arduino-audio-tools#216]
Hello.

I am trying to make a simple function generator that will send sine wave to Bluetooth speaker.

This example looks good, but no mate what I try, I can't make it to compile.
I am using Arduino ide 1.8.13 and ESP32 library v2.0.3

Can you please help me solve this error?

This is the error I get:

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:42,

                 from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/VolumeControl.h:66:37: error: reference to 'VolumeControl' is ambiguous

 class DefaultVolumeControl : public VolumeControl {

                                     ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioStreams.h:8,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioOutput.h:7,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioFilter/Equilizer.h:3,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools.h:16,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:11:

C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/VolumeControl.h:11:7: note: candidates are: 'class audio_tools::VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:42,

                 from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/VolumeControl.h:27:7: note:                 'class VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:42,

                 from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/VolumeControl.h:87:47: error: reference to 'VolumeControl' is ambiguous

 class SimpleExponentialVolumeControl : public VolumeControl {

                                               ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioStreams.h:8,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioOutput.h:7,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioFilter/Equilizer.h:3,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools.h:16,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:11:

C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/VolumeControl.h:11:7: note: candidates are: 'class audio_tools::VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:42,

                 from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/VolumeControl.h:27:7: note:                 'class VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:42,

                 from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/VolumeControl.h:106:36: error: reference to 'VolumeControl' is ambiguous

 class LinearVolumeControl : public VolumeControl {

                                    ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioStreams.h:8,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioOutput.h:7,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioFilter/Equilizer.h:3,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools.h:16,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:11:

C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/VolumeControl.h:11:7: note: candidates are: 'class audio_tools::VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:42,

                 from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/VolumeControl.h:27:7: note:                 'class VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:42,

                 from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/VolumeControl.h:121:32: error: reference to 'VolumeControl' is ambiguous

 class NoVolumeControl : public VolumeControl {

                                ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioStreams.h:8,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioOutput.h:7,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioFilter/Equilizer.h:3,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools.h:16,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:11:

C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/VolumeControl.h:11:7: note: candidates are: 'class audio_tools::VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:42,

                 from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/VolumeControl.h:27:7: note:                 'class VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:124:41: error: reference to 'VolumeControl' is ambiguous

         virtual void set_volume_control(VolumeControl *ptr){

                                         ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioStreams.h:8,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioOutput.h:7,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioFilter/Equilizer.h:3,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools.h:16,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:11:

C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/VolumeControl.h:11:7: note: candidates are: 'class audio_tools::VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:42,

                 from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/VolumeControl.h:27:7: note:                 'class VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:124:41: error: 'VolumeControl' has not been declared

         virtual void set_volume_control(VolumeControl *ptr){

                                         ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:169:9: error: reference to 'VolumeControl' is ambiguous

         VolumeControl *volume_control_ptr = nullptr;

         ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioStreams.h:8,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioOutput.h:7,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioFilter/Equilizer.h:3,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools.h:16,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:11:

C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/VolumeControl.h:11:7: note: candidates are: 'class audio_tools::VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:42,

                 from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/VolumeControl.h:27:7: note:                 'class VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:195:17: error: reference to 'VolumeControl' is ambiguous

         virtual VolumeControl* volume_control() {

                 ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioStreams.h:8,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/AudioOutput.h:7,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioFilter/Equilizer.h:3,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools.h:16,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:11:

C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioTools/VolumeControl.h:11:7: note: candidates are: 'class audio_tools::VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:42,

                 from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/VolumeControl.h:27:7: note:                 'class VolumeControl'

 class VolumeControl {

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPSink.h:17,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\src/AudioLibs/AudioA2DP.h:13,

                 from C:\Program Files (x86)\Arduino\libraries\audio_tools\examples\examples-stream\streams-generator-a2dp\streams-generator-a2dp.ino:12:

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h: In member function 'virtual void BluetoothA2DPCommon::set_volume_control(int*)':

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:125:13: error: 'volume_control_ptr' was not declared in this scope

             volume_control_ptr = ptr;

             ^~~~~~~~~~~~~~~~~~

C:\Program Files (x86)\Arduino\libraries\ESP32-A2DP\src/BluetoothA2DPCommon.h:125:13: note: suggested alternative: 'VolumeControl'

             volume_control_ptr = ptr;

             ^~~~~~~~~~~~~~~~~~

             VolumeControl

exit status 1

Error compiling for board DOIT ESP32 DEVKIT V1.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by pschatzmann** [comment]
I guess you still work on some old versions of the libraries...

**Comment by Denis-2021** [comment]
I have redownloaded fresh new Arduino IDE v1.8.19 and ESP32 library v2.0.3
and still get the same error :(

**Comment by pschatzmann** [comment]
Hmm, just take ESP32-A2DP from the main branch

**Comment by Denis-2021** [comment]
Thank you very much.
It solved the problem! :)
