### ISSUE TITLE
Low volume level in streams-generator-a2dp

### ISSUE THREAD

**Issue by Denis-2021** [pschatzmann/arduino-audio-tools#217]
Hello again :)
First of all thank you very much for the great work you have done!
I have searches all over the internet and your libraries are the only ones that worked for A2DP Source.

I have tried 2 examples: 
1. streams-generator-a2dp from this library
I like it very much but when I call out.setVolume(1); I get a low volume.
If I understood correctly this should set the volume to maximum, but I get about 70% volume.

2. bt_music_sender from ESP32-A2DP library.
It works but the generated tone has sometimes cracking and the ESP32 crashes sometimes, found the disableCore0WDT(); workaround, but is in not ideal.
But this example when called a2dp_source.set_volume(255);  outputs a very high volume (100%) on my bluetooth speaker.

*Also I found that sometimes after several uploads the ESP32 registers get "messed up" and no mater when I do I get only 20% volume, even after several reuploads.
What I found is that this problem can be fixed by erasing the whole ESP32 with the flash_download_tool_3.9.2 tool. 
Than I gen back the 70% on streams-generator-a2dp and 100% on bt_music_sender.

My question is, how can I get the same volume level on the streams-generator-a2dp example?

I have seen that you talk about AI_THINKER_ES8388_VOLUME_HACK in other thread, but I don't know how to apply it to this situation and if it can even help in this case?

**Comment by Denis-2021** [comment]
Thank you for your quick reply.
You are correct the maximum value is 1.28 :)

**Comment by pschatzmann** [comment]
Change has been comitted
