### ISSUE TITLE
New AudioKit board?

### ISSUE THREAD

**Issue by Huibs** [pschatzmann/arduino-audio-tools#228]
My audiokit board says on the front: ESP32 Audio Kit V2.2 A149 and on the back of ESP32-antenna: ESP32-A1S **2974**.  This number is not named in your list of boards. Do you know what board to select as AUDIOKIT_BOARD ?

**Comment by pschatzmann** [comment]
No. If it is a new board I suggest to try with 5.
If this is not working I suggest to try any other setting. Please report back if you get it to work so that I can update the documentation

**Comment by perlix** [comment]
I have exactly the same board and I can confirm that it works with #define AUDIOKIT_BOARD 5.

**Comment by perlix** [comment]
Will test it asap (probably this evening)

**Comment by pschatzmann** [comment]
What a pity:  I wanted to build a guitar effects pedal. 
So we can only use the old AC101 boards or the original Espressif LyraT boards for this...
