### ISSUE TITLE
[I2S] No output produced in Slave mode

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [pschatzmann/arduino-audio-tools#231]
Hello,

I'm trying out the I2S sine wave example and I can't get the slave mode to work. I'm debugging the output with a logic analyzer and this is what I get:

### Master mode
![image](https://user-images.githubusercontent.com/2017051/173222091-89e2b193-53fb-4a4f-8b5b-101ea7015071.png)

### Slave Mode (BCLK and LRCLK are external)

![image](https://user-images.githubusercontent.com/2017051/173222027-7f10e5fa-f622-4472-9e3a-f68664b1b8c3.png)

The only thing I changed between the two is going from master -> slave, and connecting BCLK and LRCLK.

Any idea what could be going on ?

**Comment by pschatzmann** [comment]
I don't really have any experience with this, but I suggest to compare the frequencies of the master clock between the 2 devices and if they do not match set it with cfg.fixed_mclk = freq to make them match

**Comment by pschatzmann** [comment]
Closed due to inactivity
