### ISSUE TITLE
Noice on output

### ISSUE THREAD

**Issue by IsiTapier** [pschatzmann/arduino-audio-tools#251]
I'm getting a lot of noice on the aux out. Any way to prevent this from happening?

**Comment by IsiTapier** [comment]
oh it seems to be on the input not on the output

**Comment by pschatzmann** [comment]
You did not really provide any hardware information, so I assume that you refer to the known hardware bug of the AudioKit:
https://github.com/Ai-Thinker-Open/ESP32-A1S-AudioKit/issues/31

**Comment by perlix** [comment]
In case OP does refer to the newer Audiokit: using the [thaaraak/es8388](https://github.com/thaaraak/es8388) library solved the input noise issue on my 'type 5' Audiokits. It may not entirely mute the mics, but their sensitivity is reduced to almost zero, making a LINE IN to LINE OUT loopback sound crystal clear.

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/arduino-audio-tools/issues/251
