### ISSUE TITLE
multi client Audio Server

### ISSUE THREAD

**Issue by IsiTapier** [pschatzmann/arduino-audio-tools#252]
I rewrote your Audio Server Class to support multiple client connections at the same time.
Maybe your are interessted and might find some time to overlook it and incoorperating it into your library.
I changed mainly the audio server class but also adjusted some other classes to work with it.
[https://github.com/IsiTapier/ESP32-Wifi-Audio/blob/master/lib/audioTools/src/AudioHttp/AudioServer.h](url)
My project consists of an esp32 lyrat board broadcasting an audio stream via aux in to multiple audio kit boards streaming it over aux out to speakers. Maybe aswell an interressting addition for the examples.

**Comment by pschatzmann** [comment]
Cool. I started a Web Server project which supports multiple clients. I just never had the time to integrate it into the audio tools
