### ISSUE TITLE
Compilation errors with arduino-esp32 v2.0.4

### ISSUE THREAD

**Issue by obdevel** [pschatzmann/arduino-audio-tools#258]
It seems that the arduino-esp32 project has changed some compiler flags in v2.0.4 so that some warnings are now errors (e.g. unused variables). I could post the compiler output but that only covers the library code used by my project and I'm sure there are other parts of the code library that are affected by this.

Simple workaround is to revert to 2.0.3.

**Comment by pschatzmann** [comment]
I would expect that setting the Compiler Warnings in Preferences to default will help...
