### ISSUE TITLE
need example for adc-a2dp

### ISSUE THREAD

**Issue by aqildad-create** [pschatzmann/arduino-audio-tools#262]
No example found for this [adc-a2dp] pattern .

**Comment by pschatzmann** [comment]
It is impossible to provide all combinations as example and this is absolutely not necessary. Try to understand how things work and you should be able to come up with the solution yourself. 
Hint: take the I2SStream example and replace it with AnalogAudioStream.

ps. This is an open source project: So if you think this example is important, create it and submit a pull request...
