### ISSUE TITLE
CodecSBC probably false default parameter

### ISSUE THREAD

**Issue by IsiTapier** [pschatzmann/arduino-audio-tools#272]
![grafik](https://user-images.githubusercontent.com/41296026/180665689-1167d3ca-da57-4a46-b306-9c92e88b047c.png)
The parameters are using these macros which are 0x01 and 0x03
But in setup it checks for the block/subbands amount and translates it into the macro value
![grafik](https://user-images.githubusercontent.com/41296026/180665754-87689acf-3c61-49f8-8330-9be59ae7efdd.png)
In case of these values it ends up being the same, but it might irritate some people. Probably change it to 8 and 16

**Comment by pschatzmann** [comment]
Default has been changed to 16
