### ISSUE TITLE
Sandbox sample communication UDP

### ISSUE THREAD

**Issue by ErichHeiz** [pschatzmann/arduino-audio-tools#276]
/**
 * @file example-udp-send.ino
 * @author Phil Schatzmann
 * @brief Sending audio over udp
 * @version 0.1
 * @date 2022-03-09
 *
 * @copyright Copyright (c) 2022
 *
 * ATTENTION: DRAFT - not tested yet
 */

On compiling i get the error:
class audio_tools::Throttle' has no member named 'defaultConfig'

  auto cfg = throttle.defaultConfig();

**Comment by pschatzmann** [comment]
The example is compiling now, but please note that this is part of the sandbox, so it is not guaranteed to work and might still have some other issues...

**Comment by ErichHeiz** [comment]
ok thanks!
