### ISSUE TITLE
Adjust simple rate in sd -a2dp

### ISSUE THREAD

**Issue by luke2023** [pschatzmann/arduino-audio-tools#282]
Is it possible to adjust the simple rate in player-sd-a2dp example?
I am now making a esp32 watch but 44.1khz uses too much power, thank you!
LinChe
(KSAC)

**Comment by pschatzmann** [comment]
No, the ESP32 A2DP API does not support this to my knowledge.
You could try to decrease the CPU Frequency to save on power...

**Comment by luke2023** [comment]
Thank you!
CPU test :

https://youtu.be/fl0i-7D50IU
