### ISSUE TITLE
download mp3 from url to sd 

### ISSUE THREAD

**Issue by aqildad-create** [pschatzmann/arduino-audio-tools#288]
your example which play mp3 from SD card is working but now further i Need example which download mp3 from URL to SD card . 

Do you have any relevant example or how can we achieve this ?

**Comment by pschatzmann** [comment]
No I don't by I would expect that you can just copy from a URLStream to a File and don't forget to close the file at the end....

**Comment by aqildad-create** [comment]
how to copy URLStream to a file ? Which example is this ?

**Comment by pschatzmann** [comment]
There is no example: I suggest that you read a tutorial about Arduino and Files first. 
You can try to copy using the StreamCopy class or simply by calling readBytes(uint8_t buffer, size_t len) and write(uint8_t buffer, size_t len) in a loop...

**Comment by pschatzmann** [comment]
I am neither providing MySQL nor basic ESP32 support.  Please use Google to find the answer yourself! 
There you should find e.g. https://esp32io.com/tutorials/esp32-mysql
