### ISSUE TITLE
increase audio volume

### ISSUE THREAD

**Issue by IsiTapier** [pschatzmann/arduino-audio-tools#289]
My received audio level is to low
I need to increase the volume either on reading it from i2c and sending it or after receiving and before outputing it over i2c again.
Basicly a way to increase the audio volume of a stream

**Comment by pschatzmann** [comment]
Is this for AudioKitStream or I2SStream ?
I suggest that you read the documentation: https://github.com/pschatzmann/arduino-audio-tools/wiki/Volume-Control
If you use the VolumeStream you need to configure allow_boost = true to allow values > 1.0

**Comment by IsiTapier** [comment]
audio kit stream

**Comment by pschatzmann** [comment]
Did you already set it to max volume  audioKit.setVolume(1.0) ?
