### ISSUE TITLE
Read A2dp volume problem

### ISSUE THREAD

**Issue by luke2023** [pschatzmann/arduino-audio-tools#292]
Hello,Thank you for your Library!
I am now having a problem of reading the volume of the a2dp player
Code:
`
void setup (){
⋯⋯
player.setVolume(1);
}
void loop(){
	player.copy();
	Serial.println(player.volume());
}
`
Out put:
ovf
ovf
ovf⋯⋯⋯⋯
And I tested again:
Out:
0.00
0.00
I don't understand what's wrong .
Thank you
LinChe

**Comment by pschatzmann** [comment]
For the time being, try to call e.g. player.setVolume(0.6); in the setup, this should avoid the problem.

**Comment by luke2023** [comment]
@pschatzmann thank you so much for the work!I found  another problem is that if I set it to 0.05 in setup, I can't use my earphones to set it very loud ,max is around 0.2,Thank You!

**Comment by luke2023** [comment]
Going to make a open source watch with Bluetooth player!![image](https://user-images.githubusercontent.com/110216618/183380840-2e9bbd08-c9cf-4d91-968f-0df7fc5976ea.jpeg)

**Comment by pschatzmann** [comment]
I suggest that you share your project here 
https://github.com/pschatzmann/arduino-audio-tools/discussions/categories/show-and-tell

**Comment by luke2023** [comment]
@pschatzmann Thank you for your suggestions! Although I set it to 0.6 it still returns 'ovf' thanks!
LinChe

**Comment by luke2023** [comment]
@pschatzmann Ok

**Comment by pschatzmann** [comment]
the player.volume() issue has been corrected

**Comment by luke2023** [comment]
@pschatzmann Thank you!I am looking forward to the update!

**Comment by luke2023** [comment]
@pschatzmann good luck!

**Comment by luke2023** [comment]
@pschatzmann Alsome!Thank you for the update!I'll try it next time! 
LinChe (KSAC)
