### ISSUE TITLE
how to download from streams-i2s-webserver_wav

### ISSUE THREAD

**Issue by xandyxor** [pschatzmann/arduino-audio-tools#306]
How to download  wav stream file from streams-i2s-webserver_wav？
<img width="641" alt="image" src="https://user-images.githubusercontent.com/22829656/186096308-8cb5968a-91d2-41c8-aade-96ebd0ed858a.png">

**Comment by pschatzmann** [comment]
Strange: never seen this so far. 
If you set your sketch to log level info, do you see that it is providing (copying data) data  ?

**Comment by xandyxor** [comment]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/22829656/186115043-bc6819eb-4fbf-4045-8bf3-b836d45dc5c2.png">

i want to download wav from webpage
but 
![image](https://user-images.githubusercontent.com/22829656/186116940-6db055e1-21ce-45ca-b08e-45caec5173e2.png)

Why is the "save an audio file" button not enabled?

**Comment by pschatzmann** [comment]
I can't provide support for webbrowsers
