### ISSUE TITLE
How to increase the microphone volume when using streams-i2s-webserver_wav

### ISSUE THREAD

**Issue by TheAxial** [pschatzmann/arduino-audio-tools#312]
Hello. please tell me how to increase the output volume of the i2s microphone?
I tried using
ConverterScaler<int16_t> volume(1.0, 0, 32767);
And
volume.setFactor(100.0); (substituted values from 0.5 to 100.0)
Here is the full code:
`/**
 * @file streams-i2s-webserver_wav.ino
 *
 *  This sketch reads sound data from I2S. The result is provided as WAV stream which can be listened to in a Web Browser
 *
 * @author Phil Schatzmann
 * @copyright GPLv3
 */

#include "AudioTools.h"
using namespace audio_tools;  
 
AudioWAVServer server("ssid","pass"); // the same a above

I2SStream i2sStream;    // Access I2S as stream
ConverterFillLeftAndRight<int16_t> filler(LeftIsEmpty); // fill both channels - or change to RightIsEmpty
ConverterScaler<int16_t> volume(1.0, 0, 32767);

void setup(){
  Serial.begin(115200);
  AudioLogger::instance().begin(Serial, AudioLogger::Info);
  volume.setFactor(100.0);
  Serial.println("starting I2S...");
  auto config = i2sStream.defaultConfig(RX_MODE); //I2S_STD_FORMAT, I2S_MSB_FORMAT, I2S_PHILIPS_FORMAT
  config.i2s_format = I2S_PCM_SHORT; // if quality is bad change to I2S_LSB_FORMAT https://github.com/pschatzmann/arduino-audio-tools/issues/23
  config.sample_rate = 22050;
  config.channels = 1;
  config.bits_per_sample = 32;
  i2sStream.begin(config);
  Serial.println("I2S started");

  // start data sink
  server.begin(i2sStream, config, &filler);
}

// Arduino loop  
void loop() {
  // Handle new connections
  server.doLoop();  
}`

**Comment by pschatzmann** [comment]
With a factor from 0.0 to 1.0 the values are decreased. 
With a factor > 1.0 the values are amplified: Typical values might be 1.5 or 2.0 (which will double the values)
I think a factor of 100.0 is just crazy and will cause that most values are clipped.  

If you get the values from I2S, they are oscillating between 0, so the scaler would need to be
ConverterScaler<int16_t> volume(1.0, -32768, 32767);

**Comment by TheAxial** [comment]
The volume is not adjustable at all. Even if I install volume.setFactor(0.0);
The sound will still be the same as without this line

**Comment by TheAxial** [comment]
I'm sorry, I accidentally
The volume is not adjustable at all. Even if I install volume.setFactor(0.0);
The sound will still be the same as without this line

**Comment by pschatzmann** [comment]
That's because you do not use volume anywhere: You will need to pass it  as argument to the server.begin(). Since you want to use multiple converters you will need to wrap them in a MultiConverter

**Comment by TheAxial** [comment]
No changes. Generally. I replaced the &filler argument with &volume, it didn't help. Changed the values in ConverterScaler<int16_t> volume(1.0, -32768, 32767); to completely different ranges from -1023..1023 to -10000000..10000000. Changed volume.setFactor(5.0);, tried 1.5, 2.0, 5.0, 20.0. Reactions 0. Please help me

**Comment by pschatzmann** [comment]
Oh, I just noticed that you have config.bits_per_sample = 32; so this changes everything and you need to ajust the range values! -2147483648l to 2147483647l

**Comment by TheAxial** [comment]
An error pops up as soon as I change to 32

C:\Users\TheAxial\Documents\Arduino\streams-i2s-webserver_wav\streams-i2s-webserver_wav.ino: In function 'void setup()':
streams-i2s-webserver_wav:21:42: error: no matching function for call to 'audio_tools::AudioWAVServer::begin(audio_tools::I2SStream&, audio_tools::I2SConfig&, audio_tools::ConverterScaler<int>*)'
   server.begin(i2sStream, config, &volume);
                                          ^
In file included from C:\Users\TheAxial\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioHttp/AudioHttp.h:4,
                 from C:\Users\TheAxial\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioTools.h:30,
                 from C:\Users\TheAxial\Documents\Arduino\streams-i2s-webserver_wav\streams-i2s-webserver_wav.ino:1:
C:\Users\TheAxial\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioHttp/AudioServer.h:271:14: note: candidate: 'void audio_tools::AudioEncoderServer::begin(Stream&, int, int, int, audio_tools::BaseConverter<short int>*)'
         void begin(Stream &in, int sample_rate, int channels, int bits_per_sample=16, BaseConverter<int16_t> *converter=nullptr) {
              ^~~~~
C:\Users\TheAxial\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioHttp/AudioServer.h:271:14: note:   no known conversion for argument 2 from 'audio_tools::I2SConfig' to 'int'
C:\Users\TheAxial\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioHttp/AudioServer.h:289:14: note: candidate: 'void audio_tools::AudioEncoderServer::begin(Stream&, audio_tools::AudioBaseInfo, audio_tools::BaseConverter<short int>*)'
         void begin(Stream &in, AudioBaseInfo info, BaseConverter<int16_t> *converter=nullptr) {
              ^~~~~
C:\Users\TheAxial\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioHttp/AudioServer.h:289:14: note:   no known conversion for argument 3 from 'audio_tools::ConverterScaler<int>*' to 'audio_tools::BaseConverter<short int>*'
C:\Users\TheAxial\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioHttp/AudioServer.h:306:14: note: candidate: 'void audio_tools::AudioEncoderServer::begin(audio_tools::AudioServerDataCallback, int, int, int)'
         void begin(AudioServerDataCallback cb, int sample_rate, int channels, int bits_per_sample=16) {
              ^~~~~
C:\Users\TheAxial\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioHttp/AudioServer.h:306:14: note:   no known conversion for argument 1 from 'audio_tools::I2SStream' to 'audio_tools::AudioServerDataCallback' {aka 'void (*)(Print*)'}
exit status 1
no matching function for call to 'audio_tools::AudioWAVServer::begin(audio_tools::I2SStream&, audio_tools::I2SConfig&, audio_tools::ConverterScaler<int>*)'

**Comment by pschatzmann** [comment]
OK, it seem that AudioServer only supports 16bits. I suggest to move back to 16 bits processing.
If you insist on using I2S with 24 bits, you will need to feed WebServer with a converted stream to 16bits.

**Comment by TheAxial** [comment]
I would be happy to stay on 16 bits, but I have a crackle in the speakers. 
Microphone: INMP441

**Comment by pschatzmann** [comment]
I suggest that you forget about the converters. Read the chapter about volume control: https://github.com/pschatzmann/arduino-audio-tools/wiki/Volume-Control
In the config you need to indicate allow_boost = true to allow values > 1.0
Then you can pass the VolumeStream object to the WebServer begin.

**Comment by TheAxial** [comment]
If I understood you correctly, then I get an error that such a parameter cannot be passed
![image](https://user-images.githubusercontent.com/54469034/186919120-3e6ea77b-2d32-4a3d-a8aa-6ad6aef37ac2.png)

**Comment by pschatzmann** [comment]
That's for the configuration of the VolumeStream!

**Comment by pschatzmann** [comment]
auto cfgVol = volume.defaultConfig();
cfgVol.allow_boost = true;
cfgVol.sample_rate = 22050;
cfgVol.channels = 1;
cfgVol.bits_per_sample = 32;
volume.begin(cfgVol);

**Comment by TheAxial** [comment]
If I understand you correctly, then it compiles, but the page in the browser does not load

#include "AudioTools.h"
using namespace audio_tools;

AudioWAVServer server("ssid", "pass");
I2SStream i2s;
VolumeStream volume(i2s);

void setup() {
  Serial.begin(115200);
  AudioLogger::instance().begin(Serial, AudioLogger::Info);
  Serial.println("starting I2S...");
  auto cfgVol = volume.defaultConfig();
  cfgVol.allow_boost = true;
  cfgVol.sample_rate = 22050;
  cfgVol.channels = 1;
  cfgVol.bits_per_sample = 32;
  volume.begin(cfgVol);
  volume.setVolume(1.0);

  server.begin(volume, cfgVol);
}

void loop() {
  server.doLoop();
}

**Comment by pschatzmann** [comment]
Yes, you will need to keep the logic to start i2s, otherwise the volume has nothing to process

**Comment by TheAxial** [comment]
Right? I commented out cfgval.allow_boost = true; because if it was 1.0, then everything worked, and if a little more or a little less, then there was no sound. However, it still does not respond to different volume values

#include "AudioTools.h"
using namespace audio_tools;

AudioWAVServer server("ssid", "pass");
I2SStream i2s;
VolumeStream volume(i2s);

void setup() {
  Serial.begin(115200);
  AudioLogger::instance().begin(Serial, AudioLogger::Info);
  Serial.println("starting I2S...");
  auto cfgVol = volume.defaultConfig();
  //cfgVol.allow_boost = true;
  cfgVol.sample_rate = 22050;
  cfgVol.channels = 1;
  cfgVol.bits_per_sample = 32;
  volume.begin(cfgVol);
  volume.setVolume(5.0);

  auto config = i2s.defaultConfig(RX_MODE);
  config.i2s_format = I2S_PCM_SHORT;
  config.sample_rate = 22050;
  config.channels = 1;
  config.bits_per_sample = 32;
  i2s.begin(config);
  
  server.begin(volume, config);
}

void loop() {
  server.doLoop();
}

**Comment by pschatzmann** [comment]
Did you try setVolume(0.0) ? That should give silence...
If you comment out //cfgVol.allow_boost = true; then any value > 1.0 is just ignored, so this setting is important if you want to use values > 1.0. The values are exponential so 5.0 is already very big. I would try with small steps: 1.1, 1.2, 1.2

**Comment by TheAxial** [comment]
No, there is still sound on 0.0. It doesn't exist only if I comment out allow_boost. But in this case, it does not work at any values other than 1.0

**Comment by pschatzmann** [comment]
You are right, there were a couple of bugs. I have just committed some corrections: If the allow_boost is used I am using a linear volume logic now because the exponential implementations only make sense for values between 0 and 1.

However I have the impression, that the browser already tries to amplify the values itself, so this might be only of limited value...

I used the sine generator to test:
```
#include "AudioTools.h"
#include "AudioLibs/AudioKit.h"

AudioWAVServer server("wifi", "pwd");
SineWaveGenerator<int32_t> sineWave(2000000000);            // subclass of SoundGenerator with max amplitude of 32000 / 2147483647
GeneratedSoundStream<int32_t> sound(sineWave);             // Stream generated from sine wave
VolumeStream volume(sound);
uint16_t sample_rate=22050;
uint8_t channels = 1;                                      // The stream will have 2 channels 
uint8_t bits_per_sample = 32;

void setup() {
  Serial.begin(115200);
  AudioLogger::instance().begin(Serial, AudioLogger::Info);
    
  sineWave.begin(channels, sample_rate, N_B4);

  auto config = volume.defaultConfig();
  config.allow_boost = true;  // uses linear control allowing values > 1.0
  config.sample_rate = sample_rate;
  config.channels = channels;
  config.bits_per_sample = bits_per_sample;
  volume.begin(config);
  volume.setVolume(10);

  server.begin(volume, config);
}

void loop() {
  server.doLoop();
}
```
