### ISSUE TITLE
noise on one channel - streams-i2s-serial and streams-i2s-webserver_wav

### ISSUE THREAD

**Issue by alowva** [pschatzmann/arduino-audio-tools#323]
Great library, thanks very much, however I am having issues and hope you can help

Lolin d32 esp32 dev board and a single INMP441.
wired up as in streams-i2s-webserver_wav readme.md

I have tried a second INMP441 as I originally thought I had broken one whilst soldering, but same result on both.

With streams-i2s-webserver_wav one channel, left or right depending on if configured L/R as GND or VCC as expected works and I can hear the mic input, however the other channel has VERY loud noise/static.

I have tried changing filler to RightIsEmpty but that made no difference

A screenshot of the result of streams-i2s-serial which appears to have the same issue
![image](https://user-images.githubusercontent.com/10676788/187471849-69a9be3f-4c36-43e9-9604-8d67fcb43ad0.png)

**Comment by pschatzmann** [comment]
Did you try the filter with the different options in the streams-i2s-serial sketch ?
