### ISSUE TITLE
SD and SDMMC Player examples are broken in latest ESP32 versions

### ISSUE THREAD

**Issue by pschatzmann** [pschatzmann/arduino-audio-tools#373]
It seems that the SD and SDMMC is not working any more....

e.g. player-sd-audiokit is working fine in 1.0.6
It seems that the file.getName() function does not provide the path any more. Since 2.0 it returns just the file name w/o path. Before it provided the file name including the full path.

**Comment by luke2023** [comment]
@pschatzmann You mean sdfat player and some things like that?

**Comment by pschatzmann** [comment]
No SDFAT is working perfectly. The things that do not work are SDMMC and SD !

**Comment by pschatzmann** [comment]
I just committed a code change that corrects the problem
