### ISSUE TITLE
Don't read files from sd card, because of missing '/' in file path

### ISSUE THREAD

**Issue by Sergionn** [pschatzmann/arduino-audio-tools#378]
Don't read files from sd card, because of missing '/' in file path

**Comment by pschatzmann** [comment]
I am afraid that you need to provide more details:
- what example
- for which SD library

**Comment by luke2023** [comment]
> Don't read files from sd card, because of missing '/' in file path

You mean the issue #290

**Comment by pschatzmann** [comment]
No: https://github.com/pschatzmann/arduino-audio-tools/issues/373

**Comment by pschatzmann** [comment]
I am closing this issue because I did not get the requested information and I can't reproduce the issue myself
