### ISSUE TITLE
Allow performance constants to be overridden via AudioConfigLocal.h

### ISSUE THREAD

**Issue by andrewwakeling** [pschatzmann/arduino-audio-tools#388]
Firstly, thank you for such marvelous libraries!

Is it possible to change it so that some/all of the constants mentioned in https://github.com/pschatzmann/arduino-audio-tools/wiki/Performance (e.g. URL_STREAM_BUFFER_COUNT, URL_STREAM_PRIORITY) use the #ifndef pattern, so they can be overridden using "AudioConfigLocal.h"?

If there's another way to achieve this, I'm happy to do so too. Thank you.

**Comment by pschatzmann** [comment]
Hmm, I thought that these parameters are not necessary any more: after all the Wifi of the ESP32 is now fast enough, so that an additional task is not needed.
But feel free to submit a pull request...
