### ISSUE TITLE
Testing example player-sd-i2s

### ISSUE THREAD

**Issue by podaen** [pschatzmann/arduino-audio-tools#39]
if I comment #define USE_URL_ARDUINO in the AudioConfig I get these issues

> AudioHttp.h:3: In file included from
> AudioTools.h:27: from
> player-sd-i2s.ino:66: from
>  
> URLStreamESP32.h: 169:72: error: 'MethodID' has not been declared
>    void begin(const char* urlStr, const char* acceptMime=nullptr, MethodID action=GET,  const char* reqMime="", const char*reqData="") {
>  
> URLStreamESP32.h: 207:9: error: 'HttpRequest' does not name a type
>    HttpRequest &httpRequest(){
>  
> URLStreamESP32.h: 213:9: error: 'URLStreamDefault' does not name a type
>    URLStreamDefault* p_urlStream=nullptr
>  
> URLStreamESP32.h: 169:88: error: 'GET' was not declared in this scope
>    void begin(const char* urlStr, const char* acceptMime=nullptr, MethodID action=GET,  const char* reqMime="", const char*reqData="") {
> URLStreamESP32.h: In constructor audio_tools::URLStream::URLStream(int)
>  
> URLStreamESP32.h: 148:13: error: 'p_urlStream' was not declared in this scope
>    p_urlStream = new URLStreamDefault(readBufferSize)
>  
> URLStreamESP32.h: 148:31: error: expected type-specifier before 'URLStreamDefault
>    p_urlStream = new URLStreamDefault(readBufferSize)
> URLStreamESP32.h: In constructor audio_tools::URLStream::URLStream(Client&, int)
>  
> URLStreamESP32.h: 154:13: error: 'p_urlStream' was not declared in this scope
>    p_urlStream = new URLStreamDefault(clientPar, readBufferSize)
>  
> URLStreamESP32.h: 154:31: error: expected type-specifier before 'URLStreamDefault
>    p_urlStream = new URLStreamDefault(clientPar, readBufferSize)
> URLStreamESP32.h: In constructor audio_tools::URLStream::URLStream(const char*, const char*, int)
>  
> URLStreamESP32.h: 160:13: error: 'p_urlStream' was not declared in this scope
>    p_urlStream = new URLStreamDefault(network, password, readBufferSize)
>  
> URLStreamESP32.h: 160:31: error: expected type-specifier before 'URLStreamDefault
>    p_urlStream = new URLStreamDefault(network, password, readBufferSize)
> URLStreamESP32.h: In destructor virtual audio_tools::URLStream::~URLStream()
>  
> URLStreamESP32.h: 166:17: error: 'p_urlStream' was not declared in this scope
>    if (p_urlStream!=nullptr) delete p_urlStream
>  
> URLStreamESP32.h: 166:46: error: type '<type error>' argument given to 'delete', expected pointer
>    if (p_urlStream!=nullptr) delete p_urlStream
> URLStreamESP32.h: In member function void audio_tools::URLStream::begin(const char*, const char*, int, const char*, const char*)
>  
> URLStreamESP32.h: 171:13: error: 'p_urlStream' was not declared in this scope
>    p_urlStream->begin(urlStr, acceptMime, action,reqMime, reqData )
> URLStreamESP32.h: In member function void audio_tools::URLStream::end()
>  
> URLStreamESP32.h: 203:13: error: 'p_urlStream' was not declared in this scope
>    p_urlStream->end()
>  
> AudioTools.h:28: In file included from
> player-sd-i2s.ino:66: from
> AudioPlayer.h: In member function virtual Stream* audio_tools::AudioSourceURL::selectStream(int)
>  
> AudioPlayer.h: 307:44: error: call to 'void audio_tools::URLStream::begin(const char*, const char*, int, const char*, const char*)' uses the default argument for parameter 3, which is not yet defined
>    actual_stream->begin(urlArray[pos], mime)
> Error compiling project sources
> Debug build failed for project 'player-sd-i2s'

I think I will make a pull to work arround this in the player

**Comment by podaen** [comment]
The player seem to play a file I have deleted from my sd card. :-/ Is is still on the sd card but in a subdirectory

Does this contain the filepath?

[I] AudioPlayer.h : 207 - -> isValidAudioFile: '001.mp3': 1

after that it gives a backtrace

```
Exception:Error:
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715:::0x400851c4:invoke_abort
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp32/panic.c:715:::0x40085441:abort
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/multi_heap_platform.h:54:::0x4008905f:multi_heap_assert
(inlined by) multi_heap_malloc_impl at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/multi_heap.c:432
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/multi_heap_poisoning.c:305:::0x40089614:multi_heap_malloc
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/heap_caps.c:215:::0x400815d9:heap_caps_malloc
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/heap_caps.c:325:::0x400817b5:heap_caps_calloc
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/driver/i2s.c:1330:::0x400f0530:i2s_create_dma_queue
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/driver/i2s.c:1330:::0x400f1e9c:i2s_set_clk
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/driver/i2s.c:1330:::0x400f268d:i2s_driver_install
E:\Documents\Visual Studio 2019\Projects\Arduino\libraries\arduino-audio-tools\src/AudioPWM/PWMAudioESP32.h(154): error 0x400d2e25:audio_tools
E:\Documents\Visual Studio 2019\Projects\Arduino\libraries\arduino-audio-tools\src/AudioPWM/PWMAudioESP32.h(154): error 0x400d2f9d:audio_tools
E:\Documents\Visual Studio 2019\Projects\Arduino\libraries\arduino-audio-tools\src/AudioPWM/PWMAudioESP32.h(154): error 0x400d2515:audio_tools
E:\Documents\Visual Studio 2019\Projects\Arduino\libraries\arduino-audio-tools\src/AudioPWM/PWMAudioESP32.h(154): error 0x400d23d5:audio_tools
E:\Documents\Visual Studio 2019\Projects\Arduino\libraries\arduino-audio-tools\src/AudioPWM/PWMAudioESP32.h(154): error 0x400d1dd3:libhelix
E:\Documents\Visual Studio 2019\Projects\Arduino\player-sd-i2s\Libraries\arduino-libhelix\0.1\arduino-libhelix\src/MP3DecoderHelix.h:111:::(inlined by) libhelix:
E:\Documents\Visual Studio 2019\Projects\Arduino\player-sd-i2s\Libraries\arduino-libhelix\0.1\arduino-libhelix\src/CommonHelix.h(206): error 0x400d4242:libhelix
E:\Documents\Visual Studio 2019\Projects\Arduino\player-sd-i2s\Libraries\arduino-libhelix\0.1\arduino-libhelix\src/CommonHelix.h(119): error 0x400d42b2:libhelix
E:\Documents\Visual Studio 2019\Projects\Arduino\libraries\arduino-audio-tools\src/AudioPWM/PWMAudioESP32.h(154): error 0x400d2225:audio_tools
E:\Documents\Visual Studio 2019\Projects\Arduino\libraries\arduino-audio-tools\src/AudioPWM/PWMAudioESP32.h(154): error 0x400d21d7:audio_tools
E:\Documents\Visual Studio 2019\Projects\Arduino\libraries\arduino-audio-tools\src/AudioTools/AudioCopy.h(202): error 0x400d4ff1:audio_tools
E:\Documents\Visual Studio 2019\Projects\Arduino\libraries\arduino-audio-tools\src/AudioTools/AudioCopy.h(88): error 0x400d5106:audio_tools
E:\Documents\Visual Studio 2019\Projects\Arduino\libraries\arduino-audio-tools\src/AudioTools/AudioCopy.h(285): error 0x400d5198:audio_tools
E:\Documents\Visual Studio 2019\Projects\Arduino\libraries\arduino-audio-tools\src/AudioTools/AudioPlayer.h:610:::(inlined by) audio_tools:
E:\Documents\Visual Studio 2019\Projects\Arduino\player-sd-i2s\player-sd-i2s/player-sd-i2s.ino(104): error 0x400d52ba:loop()
C:\Users\Dave2Moon\AppData\Local\arduino15\packages\esp32\hardware\esp32\1.0.6\cores\esp32/main.cpp(23): error 0x400ddbe1:loopTask(void*)
/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/port.c:355 (discriminator 1):::0x40086492:vPortTaskWrapper
0x40078000: ?? ??:0
0x40080400: ?? ??:0
0x400806a8: ?? ??:0
```

**Comment by pschatzmann** [comment]
The AudioSourceSdFat uses all files in the indicated directory and it's subdirectories.
So if you indicate the root as start and just move it to a subdirectory, it will still be found...

**Comment by podaen** [comment]
The player does not go correctly to the next file and eventually get stuck.

> Opening port
> Port open
> [I] I2SESP32.h : 244 - rx/tx mode: TX
> [I] I2SESP32.h : 245 - sample rate: 44100
> [I] I2SESP32.h : 246 - bits per sample: 16
> [I] I2SESP32.h : 247 - number of channels: 2
> [I] I2SESP32.h : 248 - is_master: Master
> [I] I2SESP32.h : 249 - mode: 0
> [I] I2SESP32.h : 253 - pin bck_io_num: 26
> [I] I2SESP32.h : 254 - pin ws_io_num: 25
> [I] I2SESP32.h : 255 - pin data_num: 22
> [I] AudioPlayer.h : 213 - -> isValidAudioFile: 'test.txt': 0
> [I] AudioPlayer.h : 225 - -> getFile: '': 0
> [W] AudioPlayer.h : 175 - -> selectStream: 0 ''
> [W] AudioPlayer.h : 515 - -> begin: no data found
> [W] AudioPlayer.h : 632 - -> timeout - moving to next stream
> [W] AudioPlayer.h : 166 - -> nextStream: 1
> [I] AudioPlayer.h : 213 - -> isValidAudioFile: 'test.txt': 0
> [I] AudioPlayer.h : 225 - -> getFile: '': 1
> [W] AudioPlayer.h : 175 - -> selectStream: 1 ''

Ps: I am looking now how to list the indexs and filesnames to know what comes next.

**Comment by pschatzmann** [comment]
Can you describe your file structure, so that I can replicate the issue. 
I did not run into any issues so far..

**Comment by podaen** [comment]
it's an sd.h example

can't dir and index the sdfat for now.

> Opening port
> Port open
> �SD Card Type: SDHC
> SD Card Size: 30436MB
> Listing directory: /
>   FILE: /test.txt  SIZE: 1048576
>   FILE: /foo.txt  SIZE: 13
>   DIR : /22
>   DIR : /01
>   DIR : /02
>   DIR : /03
>   DIR : /04
>   DIR : /05
>   DIR : /06
>   DIR : /07
>   DIR : /08
>   DIR : /09
>   DIR : /10
>   DIR : /21
>   DIR : /23
>   DIR : /24
>   DIR : /25
>   DIR : /26
>   DIR : /27
>   DIR : /28
>   DIR : /29
>   DIR : /30
>   FILE: /5.MP3  SIZE: 8731800
>   FILE: /4.MP3  SIZE: 6221683
>   FILE: /3.MP3  SIZE: 3510577
>   FILE: /010.MP3  SIZE: 3230947
>   FILE: /14.MP3  SIZE: 5714736
>   FILE: /015.MP3  SIZE: 7479477
>   FILE: /2.MP3  SIZE: 29894
>   FILE: /001.MP3  SIZE: 218437
> Creating Dir: /mydir
> Dir created
> Listing directory: /
>   FILE: /test.txt  SIZE: 1048576
>   FILE: /foo.txt  SIZE: 13
>   DIR : /mydir
>   DIR : /22
>   DIR : /01
>   DIR : /02
>   DIR : /03
>   DIR : /04
>   DIR : /05
>   DIR : /06
>   DIR : /07
>   DIR : /08
>   DIR : /09
>   DIR : /10
>   DIR : /21
>   DIR : /23
>   DIR : /24
>   DIR : /25
>   DIR : /26
>   DIR : /27
>   DIR : /28
>   DIR : /29
>   DIR : /30
>   FILE: /5.MP3  SIZE: 8731800
>   FILE: /4.MP3  SIZE: 6221683
>   FILE: /3.MP3  SIZE: 3510577
>   FILE: /010.MP3  SIZE: 3230947
>   FILE: /14.MP3  SIZE: 5714736
>   FILE: /015.MP3  SIZE: 7479477
>   FILE: /2.MP3  SIZE: 29894
>   FILE: /001.MP3  SIZE: 218437
> Removing Dir: /mydir
> Dir removed
> Listing directory: /
>   FILE: /test.txt  SIZE: 1048576
>   FILE: /foo.txt  SIZE: 13
>   DIR : /22
> Listing directory: /22
>   FILE: /22/001.MP3  SIZE: 6221683
>   FILE: /22/002.MP3  SIZE: 8731800
>   FILE: /22/003.MP3  SIZE: 3510577
>   FILE: /22/004.MP3  SIZE: 8040618
>   FILE: /22/005.MP3  SIZE: 10455057
>   FILE: /22/006.MP3  SIZE: 8392032
>   FILE: /22/007.MP3  SIZE: 13247344
>   FILE: /22/008 stopt halverwegen.mp3  SIZE: 7899208
>   FILE: /22/009.MP3  SIZE: 6507752
>   FILE: /22/010.MP3  SIZE: 7217238
>   FILE: /22/011.MP3  SIZE: 8757418
>   FILE: /22/012.MP3  SIZE: 6441632
>   FILE: /22/Welkomingsmuziek.docx  SIZE: 12285
>   DIR : /01
> Listing directory: /01
>   FILE: /01/001.MP3  SIZE: 18343
>   DIR : /02
> Listing directory: /02
>   FILE: /02/001.MP3  SIZE: 218437
>   FILE: /02/002.MP3  SIZE: 29894
>   DIR : /03
> Listing directory: /03
>   FILE: /03/001.MP3  SIZE: 27360
>   FILE: /03/002.MP3  SIZE: 25820
>   FILE: /03/003.MP3  SIZE: 31587
>   FILE: /03/004.MP3  SIZE: 96351
>   FILE: /03/005.MP3  SIZE: 59480
>   FILE: /03/006.MP3  SIZE: 27840
>   DIR : /04
> Listing directory: /04
>   FILE: /04/001.MP3  SIZE: 33513
>   FILE: /04/002.MP3  SIZE: 19144
>   FILE: /04/003.MP3  SIZE: 31452
>   FILE: /04/004.MP3  SIZE: 7403
>   FILE: /04/005.MP3  SIZE: 16459
>   FILE: /04/006.MP3  SIZE: 24917
>   FILE: /04/007.MP3  SIZE: 89467
>   FILE: /04/008.MP3  SIZE: 69472
>   FILE: /04/009.MP3  SIZE: 16550
>   FILE: /04/010.MP3  SIZE: 23523
>   FILE: /04/011.MP3  SIZE: 352801
>   FILE: /04/012.MP3  SIZE: 52563
>   FILE: /04/013.MP3  SIZE: 825080
>   FILE: /04/014.MP3  SIZE: 1033314
>   FILE: /04/015.MP3  SIZE: 560996
>   FILE: /04/016.MP3  SIZE: 747209
>   FILE: /04/017.MP3  SIZE: 2489975
>   FILE: /04/018.MP3  SIZE: 5960577
>   FILE: /04/019.MP3  SIZE: 10919362
>   FILE: /04/020.MP3  SIZE: 3368708
>   FILE: /04/021.MP3  SIZE: 5880149
>   FILE: /04/022.MP3  SIZE: 3116398
>   FILE: /04/023.MP3  SIZE: 2603285
>   FILE: /04/024.MP3  SIZE: 4248510
>   FILE: /04/Soundtrack, Le Gendarme De Saint Tropez - Marche Des Gendarmes.mp3  SIZE: 2340974
>   DIR : /05
> Listing directory: /05
>   FILE: /05/001.MP3  SIZE: 71780
>   FILE: /05/002.MP3  SIZE: 49654
>   FILE: /05/003.MP3  SIZE: 32365
>   FILE: /05/004.MP3  SIZE: 13310
>   FILE: /05/005.MP3  SIZE: 6925
>   FILE: /05/006.MP3  SIZE: 44271
>   FILE: /05/007.MP3  SIZE: 43129
>   FILE: /05/008.MP3  SIZE: 15012
>   FILE: /05/009.MP3  SIZE: 36439
>   FILE: /05/010.MP3  SIZE: 33140
>   FILE: /05/011.MP3  SIZE: 46582
>   FILE: /05/012.MP3  SIZE: 21228
>   FILE: /05/013.MP3  SIZE: 902285
>   FILE: /05/014.MP3  SIZE: 428724
>   FILE: /05/015.MP3  SIZE: 908959
>   FILE: /05/016.MP3  SIZE: 725893
>   FILE: /05/017.MP3  SIZE: 819584
>   FILE: /05/018.MP3  SIZE: 1042497
>   FILE: /05/019.MP3  SIZE: 122240
>   FILE: /05/020.MP3  SIZE: 696169
>   FILE: /05/021.MP3  SIZE: 7749197
>   FILE: /05/022.MP3  SIZE: 3285041
>   FILE: /05/023.MP3  SIZE: 5899827
>   FILE: /05/024.MP3  SIZE: 879493
>   DIR : /06
> Listing directory: /06
>   FILE: /06/001.MP3  SIZE: 18087
>   FILE: /06/002.MP3  SIZE: 32749
>   FILE: /06/003.MP3  SIZE: 31206
>   FILE: /06/004.MP3  SIZE: 32736
>   FILE: /06/005.MP3  SIZE: 13310
>   DIR : /07
> Listing directory: /07
>   FILE: /07/001.MP3  SIZE: 41205
>   FILE: /07/002.MP3  SIZE: 35817
>   FILE: /07/003.MP3  SIZE: 16845
>   FILE: /07/004.MP3  SIZE: 30821
>   FILE: /07/005.MP3  SIZE: 28897
>   FILE: /07/006.MP3  SIZE: 32756
>   FILE: /07/007.MP3  SIZE: 31210
>   FILE: /07/008.MP3  SIZE: 35057
>   FILE: /07/009.MP3  SIZE: 8180
>   FILE: /07/010.MP3  SIZE: 32743
>   FILE: /07/011.MP3  SIZE: 16840
>   FILE: /07/012.MP3  SIZE: 9431
>   DIR : /08
> Listing directory: /08
>   FILE: /08/001.MP3  SIZE: 1166169
>   FILE: /08/002.MP3  SIZE: 714026
>   FILE: /08/003.MP3  SIZE: 1356461
>   FILE: /08/004.MP3  SIZE: 3646246
>   FILE: /08/005.MP3  SIZE: 5933732
>   FILE: /08/006.MP3  SIZE: 4864000
>   FILE: /08/007.MP3  SIZE: 2808002
>   FILE: /08/008.MP3  SIZE: 9972669
>   FILE: /08/009.MP3  SIZE: 7145696
>   FILE: /08/010.MP3  SIZE: 6466730
>   FILE: /08/011.MP3  SIZE: 3316335
>   FILE: /08/012.MP3  SIZE: 8782277
>   FILE: /08/013.MP3  SIZE: 7591268
>   FILE: /08/014.MP3  SIZE: 8662538
>   FILE: /08/015.MP3  SIZE: 5305016
>   FILE: /08/016.MP3  SIZE: 8908710
>   FILE: /08/017.MP3  SIZE: 4159488
>   FILE: /08/018.MP3  SIZE: 5094367
>   FILE: /08/019.MP3  SIZE: 3599342
>   FILE: /08/020.MP3  SIZE: 3467473
>   FILE: /08/021.MP3  SIZE: 4051537
>   FILE: /08/022.MP3  SIZE: 8110946
>   FILE: /08/023.MP3  SIZE: 7493737
>   FILE: /08/024.MP3  SIZE: 9233221
>   FILE: /08/025.MP3  SIZE: 7406706
>   DIR : /09
> Listing directory: /09
>   FILE: /09/001.MP3  SIZE: 589611
>   FILE: /09/002.MP3  SIZE: 593001
>   FILE: /09/003.MP3  SIZE: 942275
>   FILE: /09/004.MP3  SIZE: 825080
>   FILE: /09/005.MP3  SIZE: 919459
>   FILE: /09/006.MP3  SIZE: 1001746
>   FILE: /09/007.MP3  SIZE: 10685744
>   FILE: /09/008.MP3  SIZE: 5369860
>   FILE: /09/009.MP3  SIZE: 3712451
>   FILE: /09/010.MP3  SIZE: 3973120
>   FILE: /09/011.MP3  SIZE: 8336230
>   FILE: /09/012.MP3  SIZE: 11910687
>   FILE: /09/013.MP3  SIZE: 3021200
>   FILE: /09/014.MP3  SIZE: 4026012
>   FILE: /09/015.MP3  SIZE: 4540416
>   FILE: /09/016.MP3  SIZE: 9557600
>   FILE: /09/017.MP3  SIZE: 7402334
>   FILE: /09/018.MP3  SIZE: 3469312
>   FILE: /09/019.MP3  SIZE: 4155392
>   FILE: /09/020.MP3  SIZE: 4159488
>   FILE: /09/021.MP3  SIZE: 6351958
>   FILE: /09/022.MP3  SIZE: 2887680
>   FILE: /09/023.MP3  SIZE: 6404096
>   FILE: /09/024.MP3  SIZE: 987046
>   FILE: /09/025.MP3  SIZE: 11040414
>   DIR : /10
> Listing directory: /10
>   FILE: /10/001.MP3  SIZE: 539551
>   FILE: /10/002.MP3  SIZE: 964183
>   FILE: /10/003.MP3  SIZE: 589611
>   FILE: /10/004.MP3  SIZE: 416749
>   FILE: /10/005.MP3  SIZE: 490779
>   FILE: /10/006.MP3  SIZE: 969150
>   FILE: /10/007.MP3  SIZE: 7018797
>   FILE: /10/008.MP3  SIZE: 4026012
>   FILE: /10/009.MP3  SIZE: 4540416
>   FILE: /10/010.MP3  SIZE: 4669440
>   FILE: /10/011.MP3  SIZE: 4006285
>   FILE: /10/012.MP3  SIZE: 4269463
>   FILE: /10/013.MP3  SIZE: 4155392
>   FILE: /10/014.MP3  SIZE: 4485120
>   FILE: /10/015.MP3  SIZE: 2887680
>   DIR : /21
> Listing directory: /21
>   FILE: /21/001.MP3  SIZE: 22751
>   FILE: /21/002.MP3  SIZE: 27744
>   FILE: /21/003.MP3  SIZE: 30817
>   FILE: /21/004.MP3  SIZE: 29284
>   FILE: /21/005.MP3  SIZE: 35812
>   FILE: /21/006.MP3  SIZE: 28893
>   FILE: /21/007.MP3  SIZE: 40808
>   FILE: /21/008.MP3  SIZE: 28894
>   FILE: /21/009.MP3  SIZE: 35435
>   DIR : /23
> Listing directory: /23
>   FILE: /23/001.MP3  SIZE: 7356554
>   FILE: /23/002.MP3  SIZE: 4161664
>   FILE: /23/003.MP3  SIZE: 3178289
>   FILE: /23/004.MP3  SIZE: 8568291
>   FILE: /23/005.MP3  SIZE: 8920628
>   FILE: /23/006.MP3  SIZE: 15937664
>   FILE: /23/007.MP3  SIZE: 8645820
>   FILE: /23/008.MP3  SIZE: 6580061
>   FILE: /23/009.MP3  SIZE: 4325425
>   FILE: /23/010.MP3  SIZE: 4862084
>   FILE: /23/011.MP3  SIZE: 8524611
>   FILE: /23/012.MP3  SIZE: 9772013
>   FILE: /23/013.MP3  SIZE: 7150364
>   FILE: /23/014.MP3  SIZE: 8591279
>   FILE: /23/015.MP3  SIZE: 7479477
>   FILE: /23/016.MP3  SIZE: 4962976
>   FILE: /23/017.MP3  SIZE: 10722061
>   DIR : /24
> Listing directory: /24
>   FILE: /24/001.MP3  SIZE: 58709
>   FILE: /24/002.MP3  SIZE: 64595
>   FILE: /24/003.MP3  SIZE: 56206
>   DIR : /25
> Listing directory: /25
>   FILE: /25/001.MP3  SIZE: 1292118
>   FILE: /25/002.MP3  SIZE: 2842101
>   FILE: /25/003.MP3  SIZE: 5726003
>   FILE: /25/004.MP3  SIZE: 5865008
>   FILE: /25/005.MP3  SIZE: 5156406
>   FILE: /25/006.MP3  SIZE: 1513112
>   FILE: /25/007.MP3  SIZE: 5477170
>   FILE: /25/008.MP3  SIZE: 8348615
>   DIR : /26
> Listing directory: /26
>   FILE: /26/001.MP3  SIZE: 7872500
>   FILE: /26/002.MP3  SIZE: 2159636
>   FILE: /26/003.MP3  SIZE: 2317085
>   FILE: /26/004.MP3  SIZE: 3074405
>   FILE: /26/005.MP3  SIZE: 2362816
>   FILE: /26/006.MP3  SIZE: 1317542
>   FILE: /26/007.MP3  SIZE: 6219617
>   FILE: /26/008.MP3  SIZE: 4448656
>   FILE: /26/009.MP3  SIZE: 8431293
>   FILE: /26/01-the_riverfront_studio_orchestra-theme_from_the_shining-322970af.mp3  SIZE: 8284288
>   FILE: /26/010.MP3  SIZE: 3230947
>   FILE: /26/011.MP3  SIZE: 10129168
>   FILE: /26/012.MP3  SIZE: 9033841
>   FILE: /26/06-movie_sounds_unlimited-theme_from_psycho_-_prelude_-_the_murder-954dc24a.mp3  SIZE: 7000192
>   FILE: /26/candyman 1992.txt  SIZE: 0
>   FILE: /26/case 39.txt  SIZE: 0
>   FILE: /26/Darth vader's theme.txt  SIZE: 0
>   FILE: /26/it.txt  SIZE: 0
>   FILE: /26/Nightmare on Elm Street Freddy Krueger .txt  SIZE: 0
>   FILE: /26/piano jaws 1975.txt  SIZE: 0
>   FILE: /26/saw 2004.txt  SIZE: 0
>   FILE: /26/The Exorcist ( 1973.txt  SIZE: 0
>   FILE: /26/the ring hans zimmers 1992.txt  SIZE: 0
>   FILE: /26/TOP5HA~1.URL  SIZE: 69
>   FILE: /26/War10ck111 - Spooky Scary Skeletons (piano cover).mp3  SIZE: 2701197
>   DIR : /26/niet
> Listing directory: /26/niet
>   FILE: /26/niet/001.MP3  SIZE: 4790192
>   FILE: /26/niet/004.MP3  SIZE: 4595314
>   FILE: /26/niet/01. Mike Oldfield - Tubular Bells (Opening Theme - From 'The Exorcist').flac  SIZE: 17161809
>   FILE: /26/niet/05- Tubular Bells (Opening Theme From The Exorcist ).mp3  SIZE: 6535363
>   FILE: /26/niet/15 - halloween.mp3  SIZE: 2342704
>   FILE: /26/niet/Exorcist Theme - Tubular Bells (Halloween Sound Mix).mp3  SIZE: 1798144
>   FILE: /26/niet/Halloween II - Laurie's Theme.mp3  SIZE: 2700852
>   FILE: /26/niet/Halloween II suite F.mp3  SIZE: 7431003
>   FILE: /26/niet/jaws - 'Theme' from Jaws (1975).mp3  SIZE: 4185534
>   FILE: /26/niet/jaws. John Williams - Into The Estuary.mp3  SIZE: 6924670
>   FILE: /26/niet/jaws. John Williams - The Empty Raft.mp3  SIZE: 3457552
>   FILE: /26/niet/jaws. John Williams - The Pier Incident.mp3  SIZE: 5845292
>   FILE: /26/niet/night - A Nightmare On Elm Street - Mark Ayres .mp3  SIZE: 10034483
>   FILE: /26/niet/night Charles Bernstein - Main Title (A Nightmare On Elm Street) -.mp3  SIZE: 8402025
>   FILE: /26/niet/night Halloween Horror Movie Themes - Theme of Nightmare On Elm Street.mp3  SIZE: 2600276
>   FILE: /26/niet/night Pino Donaggio - City of Prague Philharmonic - A Nightmare on Elm Street (Main Theme).mp3  SIZE: 4022272
>   FILE: /26/niet/Pet Sematary II (Main Title).mp3  SIZE: 5309743
>   FILE: /26/niet/The Exorcist (Main Theme).mp3  SIZE: 4139008
>   FILE: /26/niet/Theme, The Exorcist II.mp3  SIZE: 3024605
>   DIR : /27
> Listing directory: /27
>   FILE: /27/001.MP3  SIZE: 253054
>   FILE: /27/002.MP3  SIZE: 75622
>   FILE: /27/003.MP3  SIZE: 4309962
>   FILE: /27/004.MP3  SIZE: 9618414
>   FILE: /27/005.MP3  SIZE: 5207861
>   FILE: /27/006.MP3  SIZE: 5303379
>   FILE: /27/007.MP3  SIZE: 98979
>   FILE: /27/008.MP3  SIZE: 4498414
>   FILE: /27/009.MP3  SIZE: 5952911
>   FILE: /27/010.MP3  SIZE: 8718634
>   FILE: /27/011.MP3  SIZE: 4344396
>   FILE: /27/012.MP3  SIZE: 9130470
>   FILE: /27/013.MP3  SIZE: 3991596
>   FILE: /27/014.MP3  SIZE: 4329514
>   FILE: /27/015.MP3  SIZE: 9233221
>   DIR : /28
> Listing directory: /28
>   FILE: /28/001.MP3  SIZE: 65236
>   FILE: /28/002.MP3  SIZE: 3867504
>   FILE: /28/003.MP3  SIZE: 1582238
>   FILE: /28/004.MP3  SIZE: 2711246
>   FILE: /28/005.MP3  SIZE: 3899607
>   FILE: /28/006.MP3  SIZE: 2352311
>   FILE: /28/007.MP3  SIZE: 3575808
>   FILE: /28/008.MP3  SIZE: 3003165
>   FILE: /28/009.MP3  SIZE: 3776511
>   FILE: /28/010.MP3  SIZE: 2486032
>   FILE: /28/011.MP3  SIZE: 4149248
>   FILE: /28/012.MP3  SIZE: 970752
>   FILE: /28/013.MP3  SIZE: 2625288
>   FILE: /28/xmas profits.txt  SIZE: 0
>   DIR : /29
> Listing directory: /29
>   FILE: /29/001.MP3  SIZE: 3608078
>   FILE: /29/002.MP3  SIZE: 7911235
>   FILE: /29/003.MP3  SIZE: 13606095
>   FILE: /29/004.MP3  SIZE: 7895181
>   FILE: /29/005.MP3  SIZE: 4283305
>   FILE: /29/006.MP3  SIZE: 9070884
>   FILE: /29/007.MP3  SIZE: 12830151
>   FILE: /29/008.MP3  SIZE: 3999872
>   FILE: /29/009.MP3  SIZE: 6844469
>   FILE: /29/010.MP3  SIZE: 9100885
>   FILE: /29/011.MP3  SIZE: 10357070
>   FILE: /29/012.MP3  SIZE: 9705279
>   FILE: /29/013.MP3  SIZE: 6662272
>   FILE: /29/014.MP3  SIZE: 5714736
>   FILE: /29/015.MP3  SIZE: 3924014
>   FILE: /29/016.MP3  SIZE: 9953228
>   FILE: /29/017.MP3  SIZE: 8720754
>   DIR : /30
> Listing directory: /30
>   FILE: /30/001.MP3  SIZE: 3959709
>   FILE: /30/002.MP3  SIZE: 9844310
>   FILE: /30/003.MP3  SIZE: 4104621
>   FILE: /30/004.MP3  SIZE: 3835364
>   FILE: /30/005.MP3  SIZE: 10047678
>   FILE: /30/006.MP3  SIZE: 4327495
>   FILE: /30/007.MP3  SIZE: 9386500
>   FILE: /30/008.MP3  SIZE: 11506708
>   FILE: /30/009.MP3  SIZE: 6294857
>   FILE: /30/010.MP3  SIZE: 8834582
>   FILE: /5.MP3  SIZE: 8731800
>   FILE: /4.MP3  SIZE: 6221683
>   FILE: /3.MP3  SIZE: 3510577
>   FILE: /010.MP3  SIZE: 3230947
>   FILE: /14.MP3  SIZE: 5714736
>   FILE: /015.MP3  SIZE: 7479477
>   FILE: /2.MP3  SIZE: 29894
>   FILE: /001.MP3  SIZE: 218437
> Writing file: /hello.txt
> File written
> Appending to file: /hello.txt
> Message appended
> Reading file: /hello.txt
> Read from file: Hello World!
> Deleting file: /foo.txt
> File deleted
> Renaming file /hello.txt to /foo.txt
> File renamed
> Reading file: /foo.txt
> Read from file: Hello World!

**Comment by pschatzmann** [comment]
2 things are different from my setup. I did not have any txt files - so I will make a test with this. And your extensions can be in caps. I will need to extend my logic to cope with this

**Comment by podaen** [comment]
Does this in the sd.h library give me the index?

			//Serial.print(" POSITION: ");
			//Serial.println(file.position());

I have updated my dir above. You will see all positions are 0. I think they are not indexed yet...

**Comment by pschatzmann** [comment]
No, i am walking the file trie recursively until I found the requested position.

ps. I am not using the SD.h library but the SDFAT library
https://www.arduino.cc/en/reference/SD
https://github.com/greiman/SdFat
but the mechanisms are the same...

**Comment by pschatzmann** [comment]
I just committed some corrections for the navigation and made the file extension insensitive to caps...

**Comment by podaen** [comment]
Ok, I will take a look. I know now how to work with the index in shfat library. 

```
  File dir;
  File file;
  // open the directory containing the file.
  if (!dir.open(dirPath)) { // handle error}
  // Use name of file in the directory - replace O_RDWR with desired options
  if (!file.open(&dir, fileName, O_RDWR)) { // handle error}
  // use uint16_t for FAT, uint32_t for exFAT
  uint32_t index = file.dirIndex();
  file.close();
  // ...
  // open later by index
  if (!file.open(&dir, index, O_RDWR)) { // hnadle error}
```

**Comment by pschatzmann** [comment]
In my case I have a complex directory structure (comping from ITunes) with authors, albums and songs and I wanted to have a way to deal with all files in all subdirectories. So if I point to root, I should get all songs of all authors. If I start at an author directory, I get the songs only of this author...

**Comment by podaen** [comment]
First thing you need to know with fat you have.

This is an example of a FAT32 witch means that the index is a uint32_t 

![2021-11-10_163106](https://user-images.githubusercontent.com/63886347/141143069-76a6b0f0-6a70-4525-9b5b-5362de7c6ca6.jpg)

**Comment by podaen** [comment]
On what framework IDF are you are now? I cann't acces strcmp_i in 1.0.6...

**Comment by podaen** [comment]
Ok, I see now. You made it yourself. Strong move.

**Comment by podaen** [comment]
With playing by path, it possible to da that with storing only the position in to the memorie I think. Speed is not an issue. Speed is not an issue wirh playing songs if we think that evry song plays for at least a second.
