### ISSUE TITLE
[player-sdfat-i2s]complier error :AudioConfig.h:234:19: error: expected ',' before 'SPICS0'

### ISSUE THREAD

**Issue by ydpydp** [pschatzmann/arduino-audio-tools#398]
Hi guys, 
when I complie the arduino-audio-tools example project：“player-sdfat-i2s”，

arduino IDE2.0 message：
libraries\arduino-audio-tools-main\src/AudioConfig.h:234:19: error: expected ',' before 'SPICS0'
#define PIN_CS SS SPICS0

**Comment by pschatzmann** [comment]
I just committed the correction for the ESP32 S3 and C3
