### ISSUE TITLE
player-sdfat-a2dp___player-sdfat-analog__320kbps

### ISSUE THREAD

**Issue by amirjak0** [pschatzmann/arduino-audio-tools#401]
hi your codes perfect
I use this two example
___player-sdfat-a2dp___
___player-sdfat-analog___
Mp3 ### **224kbps** is good **But**
mp3 **### 320kbps** get A lot of hiccup
How can I play without hiccup

**Comment by pschatzmann** [comment]
Where are you getting the mp3 files with these insane (=Audicity classification) bitrates from ? 
I see the following options:
- convert the file to a normal bitrate
- convert to PCM WAV file
- use a vs1053 to do the decoding (though I did not test this with 320kbps)
