### ISSUE TITLE
SOSFilter calls filter->filter instead of filter->process

### ISSUE THREAD

**Issue by crazy-weasel** [pschatzmann/arduino-audio-tools#407]
Hi,

the SOSFilter calls the non existent method "filter" on the added filters, instead of the process method:

https://github.com/pschatzmann/arduino-audio-tools/blob/main/src/AudioFilter/Filter.h#L325

Greetings,
wsl

**Comment by pschatzmann** [comment]
The correction has been committed...

**Comment by crazy-weasel** [comment]
Thanks :)
