### ISSUE TITLE
ESP32S3 Playback streaming while saving mp3 file and DMA usage for streamcopy

### ISSUE THREAD

**Issue by 0x0fe** [pschatzmann/arduino-audio-tools#413]
I did not found if there is an API to achieve stream playback of an mp3 file while saving it to SD card on ESP32 (S3), that is, we provide a standard file url, start the download and whenever enough data is buffered it starts the playback at the same time.
Also, i wonder if there is any implementation of copier.copy with DMA or if it has to be called in an endless loop no matter what, besides, i wonder if copier.copy can live in a separate thread. I have noticed a separate  URLStreamESP32 class in the documentation, but the link is broken when we try to open the actual file, and i found no example using it, so i suspect i am using the wrong implementation, it works, but i would surely be better to have this appening in a separate thread rather than in the main loop as it is now on my test.
Thanks.

**Comment by pschatzmann** [comment]
Sure, you can execute the copy in your own task.
You can use a MultiOutput class to send the output to multiple destinations...

⁣Get TypeApp for Android ​

**Comment by 0x0fe** [comment]
okay, could you clairfy the usage of #define USE_URLSTREAM_TASK?
when i enable it, i get stuck when the stream should start

![image](https://user-images.githubusercontent.com/89607149/196047195-55a9f310-8d10-4dac-a493-90cdfe5055c0.png)

I am not sure if copier.copy(); shoudl still be used when enabled, but earlier i tried to enable USE_URLSTREAM_TASK and comment copier.copy(); but it did not work either.

Also, when the stream is started (USE_URLSTREAM_TASK disabled) i notice there is numerous drops in the audio whenever streamcopy doesnt get 1024 bytes, so i wonder how to mitigate this, i tried to increase #define URL_STREAM_BUFFER_COUNT 10 to 20, but it did not change anything.
My test just uses 
`url.begin("http://stream.srg-ssr.ch/m/rsj/mp3_128", "audio/mp3");`

![image](https://user-images.githubusercontent.com/89607149/196047262-2a64aa6e-8aab-4edc-a22f-5283b0cad899.png)

**Comment by pschatzmann** [comment]
the api is still the same! It just adds another queue to the processing. 

⁣Get TypeApp for Android ​

On Oct 16, 2022, 18:41, at 18:41, 0x0fe ***@***.***> wrote:
>okay, could you clairfy the usage of #define USE_URLSTREAM_TASK?
>when i enable it, i get stuck when the stream should start
>
>![image](https://user-images.githubusercontent.com/89607149/196047195-55a9f310-8d10-4dac-a493-90cdfe5055c0.png)
>
>I am not sure if copier.copy(); shoudl still be used when enabled, but
>earlier i tried to enable USE_URLSTREAM_TASK and comment copier.copy();
>but it did not work either.
>
>Also, when the stream is started (USE_URLSTREAM_TASK disabled) i notice
>there is numerous drops in the audio whenever streamcopy doesnt get
>1024 bytes, so i wonder how to mitigate this, i tried to increase
>#define URL_STREAM_BUFFER_COUNT 10 to 20, but it did not change
>anything.
>My test just uses 
>`url.begin("http://stream.srg-ssr.ch/m/rsj/mp3_128", "audio/mp3");`
>
>![image](https://user-images.githubusercontent.com/89607149/196047262-2a64aa6e-8aab-4edc-a22f-5283b0cad899.png)
>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/pschatzmann/arduino-audio-tools/issues/413#issuecomment-1280005673
>You are receiving this because you commented.
>
>Message ID:
***@***.***>
