### ISSUE TITLE
Volume control for I2S microphone

### ISSUE THREAD

**Issue by Montilien** [pschatzmann/arduino-audio-tools#414]
I try to do a baby monitor which need high sensitivity from microphone. I have read and try all recommandations from the issue #312 but I cannot compile the sketch. Please can you help me by giving the complete sketch including manual volume control for I2S webserver application?
thanks in avance
Regards

**Comment by pschatzmann** [comment]
My sketch is working for me and I am afraid that you need to learn how to use your hardware and analyse the issues yourself!
