### ISSUE TITLE
can't work on esp32s3

### ISSUE THREAD

**Issue by ydpydp** [pschatzmann/arduino-audio-tools#422]
example:(streams-i2s-a2dp)
arduino ide 2.0
board:esp32s3

libraries\ESP32-A2DP-main\src\BluetoothA2DPSink.cpp: In member function 'virtual void BluetoothA2DPSink::init_i2s()':
libraries\ESP32-A2DP-main\src\BluetoothA2DPSink.cpp:210:31: error: 'I2S_MODE_DAC_BUILT_IN' was not declared in this scope
         if (i2s_config.mode & I2S_MODE_DAC_BUILT_IN) {
                               ^~~~~~~~~~~~~~~~~~~~~
libraries\ESP32-A2DP-main\src\BluetoothA2DPSink.cpp:210:31: note: suggested alternative: 'I2S_MODE_MASTER'
         if (i2s_config.mode & I2S_MODE_DAC_BUILT_IN) {
                               ^~~~~~~~~~~~~~~~~~~~~
                               I2S_MODE_MASTER

..........................

exit status 1

Compilation error: exit status 1

**Comment by pschatzmann** [comment]
I would have expected that you read the documentation first: https://github.com/pschatzmann/ESP32-A2DP/wiki/Support-for-esp32-c3%3F
