### ISSUE TITLE
New DAC for your wiki

### ISSUE THREAD

**Issue by clarkbremer** [pschatzmann/arduino-audio-tools#43]
Hi Phil.  I just connected the Hiletgo DAC module to my ESP32, and have it working with your library.  I made a branch of your wiki and updated the page, but since I'm not a collaborator, I can't push it up to make a PR.  Are you interested in including it, and if so, how should we proceed.

**Comment by pschatzmann** [comment]
If this is just abut updating the Wiki, I suggest that you enter the information about the module in a new discussion. I will take it up from there.

**Comment by clarkbremer** [comment]
### HiLetgo PCM5102 I2S IIS Lossless Digital Audio DAC Decoder

![](https://m.media-amazon.com/images/I/61PIfWJbQ0L._SL1100_.jpg)

This DAC is very easy to use: Just connect the 3 I2S pins and the power and everything works as expected, w/o changing the configuration!  SCK to ground seems to reduce noise.

DAC  |	ESP32
-----|----------------
SCK  |	GND
BCK  |	BCK (GPIO26)
DIN  |	OUT (GPIO22)
LCK  |	WS (GPIO25)
GND  |	GND
VIN  |	5V

**Comment by pschatzmann** [comment]
I have updated the Wiki
