### ISSUE TITLE
How to mix multiple MP3 streams

### ISSUE THREAD

**Issue by 321dev** [pschatzmann/arduino-audio-tools#447]
Suppose i have this code fragment taken from one of the samples:

```
URLStream url("SSID","password");
I2SStream i2s; // final output of decoded stream
VolumeStream volume(i2s);
EncodedAudioStream dec(&volume,new MP3DecoderHelix()); // Decoding stream
StreamCopy copier(dec, url); // copy url to decoder
```
Now i want multiple EncodedAudioStream instances, and they all should output to the mixer, and then the mixer should output to the VolumeStream. Unfortunately i couldn't find an example that does this.

The MP3Decoder writes its output directly into the VolumeStream. But i can't pass an InputMixer instance as output stream.
Instead i need something to pass to InputMixer's add() method.
So, i guess i need some kind of "adapter" class that i can pass to the EncodedAudioStream constructor as well as to InputMixer::add() ?

How can i do it?

**Comment by 321dev** [comment]
Thanks for the quick response. Could you recommend another encoding that could be decoded fast enough. We're trying to mix four audio streams.

**Comment by pschatzmann** [comment]
The best is just to unencoded PCM data. 
The next best is a WAV file (with PCM data)

**Comment by 321dev** [comment]
How about ADPCM?

**Comment by pschatzmann** [comment]
Since I don't have a CODEC for this, I don't know

**Comment by 321dev** [comment]
Ok. thanks for your quick responses.
