### ISSUE TITLE
portaudio issue

### ISSUE THREAD

**Issue by josef2600** [pschatzmann/arduino-audio-tools#451]
first, thank you for your work and help.
i tried few mini sample and if works. but no streaming. my issue is with portaudio.h file. Arduino cant fined that file(files) and doesn't compile. for example : 
"\examples\examples-desktop\generator" generator.ino
`C:\Users\Josef\Documents\Arduino\libraries\audio_tools\src/AudioLibs/PortAudioStream.h:9:10: fatal error: portaudio.h: No such file or directory
 #include "portaudio.h"
          ^~~~~~~~~~~~~
compilation terminated.
`
Arduino v1.8.19
i am using WROOM board with ps ram. 
and cmake didn't compile it ether.
and is it possible to contact you for business (donation base) by email or here ? please send me an email or skype or P.M me here. thank you .
best regards, Josef.

**Comment by pschatzmann** [comment]
Portaudio is the output that you use if you compile and run an Arduino sketch on the desktop (and not on the microcontroller). 

The details can be found in the [Wiki](https://github.com/pschatzmann/arduino-audio-tools/wiki/Running-an-Audio-Sketch-on-the-Desktop)

I have implemented this that we can develop and debug out applications on the desktop first before deploying them to a microcontroller.

**Comment by josef2600** [comment]
thank you.
