### ISSUE TITLE
File name sd card

### ISSUE THREAD

**Issue by gnpaone** [pschatzmann/arduino-audio-tools#491]
I am actually trying to display the file name of mp3 in sd card on the oled but I couldn't find any function for getting file name, please help. I am using AudioPlayer
Also same issue for a2dp bluetooth sink too

**Comment by pschatzmann** [comment]
Just look the documentation of the Audio Source!

**Comment by gnpaone** [comment]
🥵 tried various ways but couldn't make it work, can you please help like for this example: https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-audiokit/basic-a2dp-audiokit and this example: https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-audiokit/player-sdfat-audiokit/player-sdfat-audiokit.ino how you would implement I can manage I think

**Comment by pschatzmann** [comment]
You should not try, but read the [Class Documentation](https://pschatzmann.github.io/arduino-audio-tools/html/namespaceaudio__tools.html) !

**Comment by gnpaone** [comment]
> You should not try, but look up the relevant function from the [Class Documentation](https://pschatzmann.github.io/arduino-audio-tools/html/namespaceaudio__tools.html) ! There you can find how to get the file name...

Yaah, there's some under sddirect and sdindex but nothing under audiosourcesdfat nor a2dpsink 🤧😵‍💫, please help

**Comment by pschatzmann** [comment]
You must be blind!
const char *toStr  provides the actual file name

**Comment by gnpaone** [comment]
Umm sorry 😳
Can you please tell for a2dpsink too? 😳😳😳
Thanks by the way, toStr() works for sdfat
