### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by fw-box** [pschatzmann/arduino-audio-tools#5]
HI,

https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples-basic-api/base-file_mp3-a2dp/base-file_mp3-a2dp.ino
I added "#define USE_ESP8266_AUDIO 1" in "base-file_mp3-a2dp.ino".
And tried to build the file in Arduino IDE, but got the errors:

`In file included from D:\Code\_Source\Arduino\_NodeMCU32\Sample_A2DP\base-file_mp3-a2dp_sd\base-file_mp3-a2dp_sd.ino:16:0:
C:\D:\CUsers\myname\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioESP8266.h:11:74: error: expected template-name before '<' token
 class AudioOutputWithCallback : public AudioOutput, public CallbackStream<Channels> {
                                                                          ^
C:\D:\CUsers\myname\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioESP8266.h:11:74: error: expected '{' before '<' token
C:\D:\CUsers\myname\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioESP8266.h:11:74: error: expected unqualified-id before '<' token

exit status 1
開發板 ESP32 Wrover Module 編譯錯誤。`

Do you have any ideas?

My environment:
Arduino IDE with ESP32.
Installed the three libraries.
https://github.com/earlephilhower/ESP8266Audio
https://github.com/pschatzmann/ESP32-A2DP
https://github.com/pschatzmann/arduino-audio-tools

Thank you very much.
B.R.
Hartman

**Comment by pschatzmann** [comment]
I undid my latest change - it should compile again...
