### ISSUE TITLE
CodecNOP.h appears to be missing

### ISSUE THREAD

**Issue by lugdunum-1964** [pschatzmann/arduino-audio-tools#516]
LS,

when trying to compile an example using de MP3Helix codec I get an error on CodecHelix.h: 
`fatal error: AudioCodecs/CodecNOP.h: No such file or directory`

As usual the compiler is right, the file is not there.

Is there a workaround?

--
regards,
Lyon

**Comment by pschatzmann** [comment]
I was cleaning up some code and must have overlooked this. Just use 
#include "AudioCodecs/CodecMP3Helix.h"
instead until I committed the correction...

**Comment by pschatzmann** [comment]
The correction has been committed...
