### ISSUE TITLE
assert failed: tcpip_send_msg_wait_sem

### ISSUE THREAD

**Issue by VictorHAS** [pschatzmann/arduino-audio-tools#522]
Esp32-WROOM-32D
SD-Card
Running example streams-url-file

Error:
[I] URLStream.h : 76 - virtual bool audio_tools::URLStream::begin(const char*, const char*, MethodID, const char*, const char*): https://pschatzmann.github.io/arduino-audio-tools/resources/audio-8000.raw
[I] Url.h : 74 - Url::parse
[I] Url.h : 110 - url->https://pschatzmann.github.io/arduino-audio-tools/resources/audio-8000.raw
[I] Url.h : 111 - host->pschatzmann.github.io
[I] Url.h : 112 - protocol->https
[I] Url.h : 113 - path->/arduino-audio-tools/resources/audio-8000.raw
[I] Url.h : 114 - port->443
[E] URLStream.h : 290 - login not supported
[I] URLStream.h : 249 - WiFiClientSecure
[I] URLStream.h : 249 - WiFiClientSecure
[I] HttpRequest.h : 193 - process connecting to host pschatzmann.github.io port 443

assert failed: tcpip_send_msg_wait_sem IDF/components/lwip/lwip/src/api/tcpip.c:455 (Invalid mbox)

Backtrace:0x400835d1:0x3ffb21f00x40089731:0x3ffb2210 0x4008e855:0x3ffb2230 0x400e67fe:0x3ffb2360 0x400f2845:0x3ffb2390 0x400f28a4:0x3ffb23b0 0x400e6535:0x3ffb2400 0x400d7efc:0x3ffb2420 0x400d7a7a:0x3ffb26b0 0x400d7b82:0x3ffb26f0 0x400d2e57:0x3ffb2710 0x400d4fe5:0x3ffb2730 0x400d52a5:0x3ffb2760 0x400d53f5:0x3ffb27a0 0x400d551a:0x3ffb27d0 0x400dafa6:0x3ffb2820 

Code: `
/**
 * @file streams-url-file.ino
 * @author Phil Schatzmann
 * @brief Demo how to download a file from the internet and store it to a file. The test was done with an AudioKit which requires
 * some specific pin settings
 * @version 0.1
 * @date 2022-09-09
 * 
 * @copyright Copyright (c) 2022
 * 
 */
#include "SD.h"
#include "AudioTools.h"

const char *ssid = "Esp32";
const char *password = "arqc7532";
URLStream url(ssid, password); // Music Stream
StreamCopy copier; //(i2s, music, 1024); // copy music to i2s
File file; // final output stream
int retryCount = 5;

// Arduino Setup
void setup(void) {
    Serial.begin(115200);
    AudioLogger::instance().begin(Serial, AudioLogger::Info);

    // intialize SD
    if(!SD.begin()){   
        LOGE("SD failed");
        return;
    }

    // open music stream
    url.begin("https://pschatzmann.github.io/arduino-audio-tools/resources/audio-8000.raw");

    // copy file
    file = SD.open("/audio-8000.raw", FILE_WRITE);
    file.seek(0); // overwirte from beginning
    copier.begin(file, url);
    copier.copyAll();
    file.close();

    file = SD.open("/audio-8000.raw");
    LOGI("file size: %d", file.size());
}

void loop() {
}

**Comment by pschatzmann** [comment]
I think you downloaded the library while I was doing come changes. I think you can resolve the issue by taking the latest version or the last released version...

**Comment by pschatzmann** [comment]
What was the logging output ? Did you see that it was copying...

**Comment by pschatzmann** [comment]
I think the issue is that the file provides avaiableForWrite() 0 which stops the copier from working. To correct this you would need to add  copier.setCheckAvailableForWrite(false);
