### ISSUE TITLE
AudioFFTBase: reading multiple results with `resultArray`

### ISSUE THREAD

**Issue by aSemy** [pschatzmann/arduino-audio-tools#525]
I would like to fetch the top 10 results after an FFT result, but I get an error about 'no member named fft'

```cpp
void handleFftResult(AudioFFTBase &fft) {

  AudioFFTResult results[10];
  fft.resultArray<10>(results);

  // ERROR In template: no member named 'fft' in 'audio_tools::AudioFFTResult'
}
```

My guess is that there's a mistake on this line:

https://github.com/pschatzmann/arduino-audio-tools/blob/c174cd42e013cf04621a77bbd969f5b38dc4c05d/src/AudioLibs/AudioFFT.h#L207

Perhaps this should be `.magnitude`?

```cpp
result[j].magnitude = -1000000;
```

I am a C++ noob so maybe I have made a mistake!

In any case, an example of how to call this function would be very much appreciated :)

**Comment by pschatzmann** [comment]
I just committed a correction to address the compile errors. I was surprised that we only get an error when this function is used.

It would be great if you could test it if it is working correctly now

**Comment by aSemy** [comment]
Nice, thanks. I've tried it out and it compiles and runs successfully. However, I'm not sure if it's working correctly because my code/wiring/monitoring isn't finished yet.
