### ISSUE TITLE
using FIR filter and volume control for a2dp_source 

### ISSUE THREAD

**Issue by mohaddeseh-rezaee** [pschatzmann/arduino-audio-tools#560]
Hi again, 
I was wondering if using features such as FIR filter and controlling volume is available for a2dp_source mode? 
Is it possible to control the volume with the BT headset? 
I am using this example and it works fine. [base-adc-a2dp](https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-basic-api/base-adc-a2dp/base-adc-a2dp.ino)
can I add [streams-audiokit-filter-audiokit.ino](https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-audiokit/streams-audiokit-filter-audiokit/streams-audiokit-filter-audiokit.ino) to previous code I mentioned ?
 I'm also wondering if it is possible to save data on sd card or no ? 
Thanks in advance!

**Comment by pschatzmann** [comment]
I don't see any issue here, so I convert it to a discussion
