### ISSUE TITLE
Talking Clock Example "echoing" words

### ISSUE THREAD

**Issue by LenStruttmann** [pschatzmann/arduino-audio-tools#570]
Talking Clock Example "echoing" words

I am working with your Talking Clock example.  I am using platformio and sending the output to a Pmod I2S2.

Every word "spoken" had an echo-like distortion.

It turns out that in AudioCopy.h, copyALL() was resending the (usually partial) last buffer retryCount times.

To fix this, I made the following changes to AudioCopy.h:

Line: 142
            return available(); //result;

Lines 187-195
                //     // wait for more data
                //     retry++;
                //     delay(retryWaitMs);
                // } else {
                //     retry = 0; // after we got new data we restart the counting
                // }
                // // stop the processing if we passed the retry limit
                // if (retry>retryCount){

**Comment by pschatzmann** [comment]
Corrected in simple-tts project by providing the "correct" parameters in the constructor for the AudioCopy class
