### ISSUE TITLE
Compilation error: 'class audio_tools::I2SConfig' has no member named 'pin_mck'

### ISSUE THREAD

**Issue by franki29** [pschatzmann/arduino-audio-tools#573]
Hi, I wanted to compile the streams-i2s-serial.ino example, but I get following error:

Compilation error: 'class audio_tools::I2SConfig' has no member named 'pin_mck'
As I need the mck signal for my external ADC , I do not know what to do.

I am using Arduino IDE 2.0.4

Thanks for helping

**Comment by pschatzmann** [comment]
The IDE is not relevant. You need to make sure that you use a recent ESP32 Implementation in the Board Manager. The actual version is 2.0.6
