### ISSUE TITLE
AUDIO STUTTER

### ISSUE THREAD

**Issue by aqildad-create** [pschatzmann/arduino-audio-tools#577]
OUT PUT IS VERY STUTTER , HOW TO IMPROVE THIS ?  AFTER APPROXIMATLY 15 HOPS THEIR IS AOUT 3 SECOND DELAY IN GETTING DATA , MAY BE THIS MAKE STUTERRING , WHAT IS THE SOLUTION ? 

/**
 * @file streams-url_wav-serial.ino
 * @author Phil Schatzmann
 * @brief decode WAV stream from url and output it on I2S
 * @version 0.1
 * @date 2021-96-25
 * 
 * @copyright Copyright (c) 2021
 
 */
#include "AudioTools.h"

// UrlStream -copy-> EncodedAudioStream -> I2S

URLStream url("ZONG-MBB","L1YRFT");
I2SStream i2s;                  // I2S stream 
WAVDecoder decoder(i2s);        // decode wav to pcm and send it to I2S
EncodedAudioStream out(i2s, decoder); // Decoder stream
StreamCopy copier(out, url);    // copy in to out

void setup(){
  Serial.begin(115200);
  AudioLogger::instance().begin(Serial, AudioLogger::Info);  

  // setup i2s
  auto config = i2s.defaultConfig(TX_MODE);
  config.sample_rate = 16000; 
  config.bits_per_sample = 32;
  
  config.pin_ws = 26;
  config.pin_bck = 27;
  config.pin_data = 25;
  
  config.channels = 1;
  i2s.begin(config);

 
// rhasspy
  url.begin("https://stasu.com/001111111.WAV","audio/wav" );
}

void loop(){
  if (decoder) {
    copier.copy();
  } else {
    Serial.println( " FILE END " );
    stop();
  }
}

17:42:06.494 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:06.541 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:06.541 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:06.541 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:06.541 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:06.541 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.527 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.527 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.527 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.527 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.527 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.527 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.572 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.572 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.572 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.572 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.572 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.572 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.619 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.619 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.619 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:09.619 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.420 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.420 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.420 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.514 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.514 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.514 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.514 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.514 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:12.514 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.153 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.153 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.153 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.200 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.200 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.200 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.200 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.200 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.200 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.200 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.247 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.247 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.247 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.247 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.247 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.247 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.293 -> [I] AudioCopy.h : 134 - StreamCopy::copy 432 -> 432 -> 864 bytes - in 1 hops
17:42:16.994 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.994 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.994 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.994 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:16.994 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.040 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.040 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.040 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.040 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.040 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.040 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.040 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.086 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.086 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.086 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.086 -> [I] AudioCopy.h : 134 - StreamCopy::copy 566 -> 566 -> 1128 bytes - in 1 hops
17:42:17.834 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.834 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.834 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.880 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.880 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.880 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.880 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.880 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.880 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.927 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.927 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.927 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.927 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.927 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.927 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:17.927 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.672 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.672 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.719 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.719 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.719 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.719 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.719 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.719 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.719 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.766 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.766 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.766 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.766 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.766 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.766 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:18.813 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.375 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.422 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.422 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.422 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.422 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.422 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.422 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.467 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.514 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:19.514 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.575 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.575 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.575 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.622 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.622 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.622 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.622 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.622 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.622 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.622 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.669 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.669 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.669 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.669 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.669 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:21.669 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.723 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.723 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.723 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.723 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.723 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.771 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.771 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.771 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.771 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.771 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.771 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.771 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.817 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.817 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.817 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:23.817 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.843 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.890 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.890 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.890 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.890 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.890 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.890 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.937 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.937 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.937 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.937 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.937 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.937 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.937 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.983 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:24.983 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.286 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.286 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.286 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.286 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.333 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.333 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.333 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.333 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.333 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.333 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.380 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.380 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.380 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.380 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.380 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.380 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:26.380 -> [I] AudioCopy.h : 134 - StreamCopy::copy 458 -> 458 -> 912 bytes - in 1 hops
17:42:27.222 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:27.268 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:27.268 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:27.268 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops
17:42:27.268 -> [I] AudioCopy.h : 134 - StreamCopy::copy 1024 -> 1024 -> 2048 bytes - in 1 hops

**Comment by pschatzmann** [comment]
Well, this seems quite obvious to me: you need to find out where your issue is coming from: it could be your Server, your network or the ESP32! 

Don't try to process more data then your infrastructure can handle.

You can always decrease the amount of data to be transmitted by reducing the sample rate or channels or bits per sample in your WAV file -  or even better use a compressed data format like mp3...
