### ISSUE TITLE
Detect SD end

### ISSUE THREAD

**Issue by oldmanskier** [pschatzmann/arduino-audio-tools#578]
Is there a way to detect the end of a SD card. Card has 200 or more songs.  I presently count the files on the SD but this take several seconds before playing begins.  I have saved the last stream number in preferences so I can begin where I turned off the player without starting over from the beginning. I compare the last stream number with the total file count and reset last stream to zero when file count is reached.  I would like to detect the last file so I could start from the beginning without the long delay to count the files.

**Comment by pschatzmann** [comment]
Feel free to extend the functionality.

**Comment by pschatzmann** [comment]
I assume you could resolve the issue with the proposed solution.
