### ISSUE TITLE
How to use codec chip in arduino-audio-tools?

### ISSUE THREAD

**Issue by BeijingUncle** [pschatzmann/arduino-audio-tools#586]
I plan to write a SD card music sender (a2dp source) on my ESP32-LyraT board, and I think the pipeline is:

sdcard ---> fatfs_stream ---> mp3_decoder(ES8388) ---> bt_stream ---> a2dp_source.

So I think maybe I can start with the example [player-sdfat-audiokit](https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-audiokit/player-sdfat-audiokit/player-sdfat-audiokit.ino).

But this audiokit example use `MP3DecoderHelix` as a codec instead of `ES8388`. I check every file related examples and all of them use `arduino-libhelix`.

Is there a example I can learn how to use es8388 as a mp3_decoder in the pipeline?

**Comment by pschatzmann** [comment]
Please do not open issues when you want to do a discussion. 
You are mixing things up! The ES8388 has nothing to do with mp3 decoging!
