### ISSUE TITLE
I2S Sample frequency wrong when mono used

### ISSUE THREAD

**Issue by MichielfromNL** [pschatzmann/arduino-audio-tools#594]
When mono is used instead of stereo on ESP32 I2S sourced from local ADC, the sample frequency is off by a factor 2.
Reason: the analogue ESP32 driver "begin" does not set the right channel_format when the config.channels parameter is 1 instead of  2

Fix:

AnalogueAudioESP32.h  #59
 .channel_format         = cfg.channels == 2 ? I2S_CHANNEL_FMT_RIGHT_LEFT : I2S_CHANNEL_FMT_ONLY_LEFT,

**Comment by pschatzmann** [comment]
feel free to submit a pull request

**Comment by pschatzmann** [comment]
Pull request has been merged
