### ISSUE TITLE
Maybe-uninitialized warning in Fade.h

### ISSUE THREAD

**Issue by chrissbarr** [pschatzmann/arduino-audio-tools#601]
This for loop is throwing warnings for a potentially uninitialised variable:

https://github.com/pschatzmann/arduino-audio-tools/blob/0fd93dfc49446fe2b5fc3a96efe5ac20feb6faa9/src/AudioTools/Fade.h#L160

```
.pio/libdeps/esp32/audio-tools/src/AudioTools/Fade.h:161:45: warning: 'ch' may be used uninitialized in this function [-Wmaybe-uninitialized]
       last[ch] = data[frames - 2 * channels + ch];
                       ~~~~~~~~~~~~~~~~~~~~~~^~~~
.pio/libdeps/esp32/audio-tools/src/AudioTools/Fade.h:160:14: note: 'ch' was declared here
     for (int ch; ch < channels; ch++) {
```

The other similar loops in Fade.h initialise `ch` to `0`:
https://github.com/pschatzmann/arduino-audio-tools/blob/0fd93dfc49446fe2b5fc3a96efe5ac20feb6faa9/src/AudioTools/Fade.h#L145

I assume that the intent of this loop is the same, and that `ch` is probably being default initialised to zero anyway. So probably not causing an error but does throw warnings.

Would you have any objection to a PR changing this loop to match the others?

I also notice earlier in the file there is this line:
https://github.com/pschatzmann/arduino-audio-tools/blob/0fd93dfc49446fe2b5fc3a96efe5ac20feb6faa9/src/AudioTools/Fade.h#L73

I am wondering if this `channels` was intended to be an int, like the similar channels variable in the other classes in this file? I expect that assigning 2 to a bool will be cast to `True`/`1`, and is probably preventing the number of channels from ever being anything other than 0/1?

**Comment by pschatzmann** [comment]
Right it should be an int and not a bool and initialization to 0 makes sense
