### ISSUE TITLE
Compile error MP3DecoderHelix

### ISSUE THREAD

**Issue by SaschaRoelofs** [pschatzmann/arduino-audio-tools#603]
Hey,
when I compile the player-sd-i2s example the compiler cannot find the MP3DecoderHelix.h file, which is in fact not in the directory. Is it missing or have you renamed it ?

```
In file included from /tmp/.arduinoIDE-unsaved2023031-6583-kchsj6.mbrki/player-sd-i2s/player-sd-i2s.ino:11:
/home/sascha/Arduino/libraries/arduino-audio-tools-main/src/AudioCodecs/CodecMP3Helix.h:6:10: fatal error: MP3DecoderHelix.h: No such file or directory
 #include "MP3DecoderHelix.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

greetings,
Sascha

**Comment by pschatzmann** [comment]
Just read the documentation and install the necessary library:
https://github.com/pschatzmann/arduino-audio-tools/wiki/Encoding-and-Decoding-of-Audio
