### ISSUE TITLE
#include errors detected "fft.h"

### ISSUE THREAD

**Issue by zensimilia** [pschatzmann/arduino-audio-tools#607]
In `AudioLibs/AudioESP32FFT.h` we have `#include "fft.h"` but this file does not exist and error occurs.

**Comment by pschatzmann** [comment]
Please read the [documentation](https://github.com/pschatzmann/arduino-audio-tools/wiki/FFT)!
It clearly states what you need to install.

**Comment by zensimilia** [comment]
Sorry! I figured out the problem.
