### ISSUE TITLE
Feature request: Is it possible to add LoRa communication method like ESPNow with Codec2 ?

### ISSUE THREAD

**Issue by happytm** [pschatzmann/arduino-audio-tools#608]
Thank you for providing this great library for using audio features of ESP32.

I would like to use this library to make audio link using Codec2 protocol between 2 ESP32 devices equipped with LoRa radios.

I have simple project using ESPNow or Lora with codec2 protocol here https://github.com/happytm/AudioTransport/tree/main/test

Is it even possible?

Thanks.

**Comment by pschatzmann** [comment]
There is nothing to do from my side, just use the standard Lora library: As you can see [LoRaClass](https://github.com/sandeepmistry/arduino-LoRa/blob/master/src/LoRa.h) is a subclass of Stream

**Comment by happytm** [comment]
Excellent. I looked for ESPNow example with Codec2 protocol but did not find one. Can you point me to such example if there is one? 

Thanks.

**Comment by pschatzmann** [comment]
There is an [example](https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-communication/esp-now-codec/communication-codec-espnow-receive/communication-codec-espnow-receive.ino) that shows how to use esp now with a codec. Just replace the used codec with any other...

**Comment by happytm** [comment]
Thank you Sir.
