### ISSUE TITLE
Issue in the URLStream destruction order 

### ISSUE THREAD

**Issue by hummusawy** [pschatzmann/arduino-audio-tools#612]
First, thank you for your amazing effort!

In the distractor of the `URLStream`  the `clientSecure` and the `clientInsecure` get deleted before calling the `end()` method, which lead to a `null pointer exception` when the `URLStream` get distracted because the `end()` method calls `        request.stop()` which calls `client_ptr->stop()` so the client should be there when the `end()` method get called. 

I pushed the `end()` method call to the beginning of the distractor and the distraction working fine with me after doing this change. 

```
        ~URLStream(){
            TRACEI();
            end();
#ifdef USE_WIFI_CLIENT_SECURE
            if (clientSecure!=nullptr){
                delete clientSecure;
                clientSecure = nullptr;
            }
#endif
            if (clientInsecure!=nullptr){
                delete clientInsecure;
                clientInsecure = nullptr;
            }
        }
```

**Comment by pschatzmann** [comment]
correction has been committed

**Comment by hummusawy** [comment]
Super!
