### ISSUE TITLE
I2SStream begin crash when i connect two spi device?

### ISSUE THREAD

**Issue by sevenberyl** [pschatzmann/arduino-audio-tools#615]
I use st7735 LCD display with TFT_eSPI library to show something,
but when i call I2SStream.begin(),esp32 crashes

here is adc input code:

  auto cfgRx = in.defaultConfig(RX_MODE);
  cfgRx.sample_rate = SAMPLE_RATE;//44100
  cfgRx.bits_per_sample = ADC_BIT_PER_SAMPLE;//32
  cfgRx.pin_mck = ADC_PIN_MCK; // 3
  cfgRx.pin_bck = ADC_PIN_BCK;// 27
  cfgRx.pin_ws = ADC_PIN_WS; //25
  cfgRx.pin_data = ADC_PIN_DATA;//26
  cfgRx.auto_clear = true;
  in.begin(cfgRx);  //this line causes a crash
  xTaskCreate(auxModeBufferReadTask, "bufferReadTask", adc_stack_size, NULL, adc_task_priority, &adcBufferReadHandle);

here is lcd init code:
#define TFT_MOSI 23
#define TFT_SCLK 18
#define TFT_CS   5  
#define TFT_DC   14 
#define TFT_RST  33  

and init:
tft.init();

if remove TFT_eSPI init()  code ,it work well ,but i can't use any display
so How do I adjust SPI settings with tft_espi library?

**Comment by pschatzmann** [comment]
I am sorry but I cant provide any TFT_eSPI support
