### ISSUE TITLE
Kit configured as inputdevice trough inputmixer seems to play at the wrong speed trough inputmixer.

### ISSUE THREAD

**Issue by onyx99** [pschatzmann/arduino-audio-tools#617]
Kit configured as inputdevice trough inputmixer seems to play at the wrong speed in stereo trough inputmixer.

uint16_t sample_rate=44100;
uint8_t channels = 2; 

mixer.add(kit);
 
// setup audio info
AudioBaseInfo info;
info.channels = channels; //2
info.sample_rate = sample_rate; //44100
info.bits_per_sample = 16;
mixer.begin(info);

Serial.println("starting AudioKit...");
auto config = kit.defaultConfig(RX_MODE);
config.input_device = AUDIO_HAL_ADC_INPUT_LINE2;
config.sample_rate = sample_rate; //44100
config.default_actions_active = false;
config.channels = channels; //2
config.sd_active = false;
kit.begin(config);
Serial.println("AudioKit started");

**Comment by pschatzmann** [comment]
Just update the library to use the latest commit!
