### ISSUE TITLE
With the latest commit the samplerate still seems to have an issue using mixer.readBytes with the kit as (line)input

### ISSUE THREAD

**Issue by onyx99** [pschatzmann/arduino-audio-tools#619]
With the latest commit the samplerate still seems wrong using mixer.readBytes with the kit as (line)input 

[2 Channels - 44k1]
1. when i use the SineWave as input then the samplerate is correct 
2. wnen i use the AudioKitStream as input then the samplerate is incorrect (an issue)

[1 Channel - 44k1]
3. when i use the SineWave as input then the samplerate is correct
4. wnen i use the AudioKitStream as input then the samplerate is correct

#include "AudioTools.h"
#include "AudioLibs/AudioKit.h"

#include "AACEncoderFDK.h"
using namespace aac_fdk;

uint8_t buffer[1024];

uint16_t sample_rate=44100;
uint8_t channels = 2;                                      // The stream will have 2 channels 

SineWaveGenerator<int16_t> sineWave1(32000);                // subclass of SoundGenerator with max amplitude of 32000
GeneratedSoundStream<int16_t> sound1(sineWave1);             // Stream generated from sine wave

AudioKitStream kit;

InputMixer<int16_t> mixer;

// Arduino Setup
void setup(void) {  
  // Open Serial 
  Serial.begin(115200);
  AudioLogger::instance().begin(Serial, AudioLogger::Info);

  // Setup sine wave
  sineWave1.begin(channels, sample_rate, N_B4);

 // start i2s input with default configuration
  Serial.println("starting AudioKit...");
  auto config = kit.defaultConfig(RX_MODE);
  config.input_device = AUDIO_HAL_ADC_INPUT_LINE2;
  config.sample_rate = sample_rate; 
  config.default_actions_active = false; 
  config.channels = channels; 
  config.sd_active = false;
  kit.begin(config);
  Serial.println("AudioKit started");

  Serial.println("started...");

  
  mixer.add(kit);
  //mixer.add(sound1);
  
   // setup audio info
  AudioBaseInfo info;
  info.channels = channels;
  info.sample_rate = sample_rate;
  info.bits_per_sample = 16;
  mixer.begin(info);

   
  AudioInfo info_;
  info_.channels = channels;
  info_.sample_rate = sample_rate;
  aac.begin(info_);

}

// Arduino loop - copy sound to out 
void loop() {

if(mixer.available()>0){
  int samplesRead =mixer.readBytes(buffer, sizeof(buffer));
  aac.write(buffer, samplesRead);
}

//  copier.copy();
}

**Comment by onyx99** [comment]
If i take the samples from the kit (kit.readBytes) then the AAC encoding is sounding correct in stereo at 44100, but when i use the mixer.readBytes then the playback speed is a bit higher than normal, if i set the samplerate of the whole project to 32000 then it looks like it plays at the correct playback speed also taking the bytes from mixer.

**Comment by pschatzmann** [comment]
So I guest it's coming from the overhead that the InputMixer is adding. 
You can try to optimize the readBytes method

**Comment by onyx99** [comment]
ok, i will try and thanks for you time.

**Comment by pschatzmann** [comment]
I am closing this issue because I don't think that I can provide any resolution in software. I am pretty sure that you run your sketch on the desktop it will have no issues because the intel processors are much faster. 

Please feel free to reopen this issue if you disagree
