### ISSUE TITLE
streams-generator-a2dp.sketch not compiling

### ISSUE THREAD

**Issue by NDC-SC** [pschatzmann/arduino-audio-tools#625]
When compiling the streams-generator-a2dp.sketch for an ESP32 Dev Module with Arduino IDE 1.8.19, the following error is given
C:\Users\xxx\Documents\Arduino\libraries\arduino-audio-tools-main\src/AudioLibs/AudioA2DP.h:152:38: error: 'class BluetoothA2DPSource' has no member named 'set_ssid_callback'; did you mean 'data_stream_callback'?

The library zip file was downloaded today (13 Feb)

Any suggestions to rectify the problem would be appreciated.

**Comment by pschatzmann** [comment]
I guess you just forgot to use the latest version of the A2DP library (which provides this method since Nov 22, 2022)

**Comment by NDC-SC** [comment]
Yes, didn't update the ESP32-A2DP library when updating the arduino-audio-tools library.

Thank you for the quick reply.
