### ISSUE TITLE
When compiling for XIAO_ESP32C3 portYIELD_FROM_ISR generates and error.

### ISSUE THREAD

**Issue by rw-donaldp** [pschatzmann/arduino-audio-tools#632]
`....Arduino\libraries\arduino-audio-tools\src/AudioTools/SynchronizedBuffers.h:374:52: error: macro "portYIELD_FROM_ISR" passed 1 arguments, but takes just 0
`
The version with no parameters is wrapped with #ifdef ESP32X which I guess is not defined for the XIAO_ESP32C3?
Similarly
`Arduino\libraries\arduino-audio-tools\src/AudioAnalog/AnalogAudioBase.h:7:11: fatal error: soc/dac_channel.h: No such file or directory`
which I guess is because the C3 does not have a dac.
There are some other issues with the missing DAC 
`Arduino\libraries\arduino-audio-tools\src/AudioI2S/I2SESP32.h:345:49: error: 'I2S_MODE_DAC_BUILT_IN' was not declared in this scope
           mode = (i2s_mode_t) (cfg.rx_tx_mode ? I2S_MODE_DAC_BUILT_IN : I2S_MODE_ADC_BUILT_IN)`

**Comment by pschatzmann** [comment]
I suggest that you select the generic C3 Dev Module when you compile or you add your board to the AudioConfig.h

**Comment by pschatzmann** [comment]
I think I have found a more reliable way!
You can use the latest commit...

**Comment by rw-donaldp** [comment]
Many thanks for the quick update. Now all compiling OK.
