### ISSUE TITLE
Total number of SD card .mp3 songs

### ISSUE THREAD

**Issue by gary7530** [pschatzmann/arduino-audio-tools#634]
```
const char *startFilePath = "/";
const char *ext = "mp3";

AudioSourceSDFAT source(startFilePath, ext, SD_CS);
AnalogAudioStream out;
MP3DecoderHelix decoder;
AudioPlayer player(source, out, decoder);
```

I want to know how many songs are on the SD card for setting `player.setIndex();`

**Comment by pschatzmann** [comment]
I am not so sure if this is a good idea. Scanning all directories to search for the number of files is the only reliable method but this is very inefficient and can take minutes. So it is much better if you use your own custom logic which can use some heuristics which is specifc to your case.
