### ISSUE TITLE
SdFat Open utf-8 file

### ISSUE THREAD

**Issue by gary7530** [pschatzmann/arduino-audio-tools#635]
https://github.com/pschatzmann/arduino-audio-tools/blob/5fca23f32c43fbb8ec8ab961dde3f329ccce96dd/src/AudioLibs/AudioSourceIdxSDFAT.h#L4-L6

`#define USE_UTF8_LONG_NAMES 1` seems invalid

I changed it directly in` SdFatConfig.h` `#define USE_UTF8_LONG_NAMES 1`

https://github.com/greiman/SdFat/blob/628effa1c277e6dc1fef461b4b755ad300735248/src/SdFatConfig.h#L37

I can play UTF-8 songs now

**Comment by pschatzmann** [comment]
I removed these defines from the code and added a comment line to the class description

**Comment by gary7530** [comment]
Working with PlatformIO
Add `build_flags =-D USE_UTF8_LONG_NAMES=1`  can also successfully play UTF-8 songs
