### ISSUE TITLE
Sinewave frequency set as unsigned int?

### ISSUE THREAD

**Issue by rw-donaldp** [pschatzmann/arduino-audio-tools#642]
Just noticed that the SineWave generator stores the frequency as a float m_frequency but the two ways of setting it which both use the setFrequency(uint16_t frequency) method defines it as an unsigned int which will loose the accuracy of the floats defined in MusicalNotes.h for example.
Is this deliberate for any reason?

**Comment by pschatzmann** [comment]
Initially I had everything as int including the frequencies of the notes. Recently I decided to change the notes to floats, but missed this one.

Please feel free to change this and submit a Pull Request

**Comment by pschatzmann** [comment]
Thanks a lot for your contribution. You PR has been merged...
