### ISSUE TITLE
DIP switches on Ai-Thinker ESP32 Audio Kit V2.2

### ISSUE THREAD

**Issue by bootrino** [pschatzmann/arduino-audio-tools#68]
Do you know what the DIP switches do?

Did you find any documentation/datasheet for the Ai-Thinker ESP32 Audio Kit V2.2?  I can't find anything.

**Comment by pschatzmann** [comment]
https://github.com/Ai-Thinker-Open/ESP32-A1S-AudioKit
https://docs.ai-thinker.com/_media/esp32-audio-kit_v2.2_sch.pdf
https://datasheet.lcsc.com/lcsc/1912111437_Everest-semi-Everest-Semiconductor-ES8388_C365736.pdf
