### ISSUE TITLE
i2c error

### ISSUE THREAD

**Issue by Udaymakxenia** [pschatzmann/arduino-audio-tools#681]
Hi Phil , I was trying to interface and LCD - i2c module with the esp32a1s (AC101) . But when I play the file from the SD card. I get an error that i2c driver install error.
``` 11:55:15.079 -> E (10412) i2c: i2c driver install error
11:55:15.079 -> Error:   AC101
```
But if I add Wire.end() line before starting file playback and this error vanishes but my lcd hangs if I stop the music playback.
I tried adding Wire.end() after the song ends but it then gives this error :
 ``` 11:55:15.079 -> E (10412) i2c: i2c driver install error
11:55:15.079 -> Error:   AC101
``` and the code hangs.

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/arduino-audiokit/wiki
