### ISSUE TITLE
multi out @ different sampling rate .

### ISSUE THREAD

**Issue by aqildad-create** [pschatzmann/arduino-audio-tools#684]
I want to send multi out but sampling rate is different . 
 
I want to read i2s microphone data and record to file in SD @sampling rate of 44100 . but at the same time send data to espnow at around 8000. 

when button is presses esp start recording at rate 44100  and send recorded data at around 80000 sampling rate at same time . After stop button press espnow will still continue to send data until file end .

My question is how can I read from file while its still recording . OR is there any other way out of this ?

**Comment by pschatzmann** [comment]
You would just copy the data from the microphone to a MultiOutput

**Comment by pschatzmann** [comment]
In the wiki
