### ISSUE TITLE
I2s-web server No Audio in browser .

### ISSUE THREAD

**Issue by aqildad-create** [pschatzmann/arduino-audio-tools#687]
No Audio out in i2s webserver  but  i2s serial is successfully working  .  I don't know how to get it work . 

below is i2s serial plotter .

![image](https://user-images.githubusercontent.com/65456998/225708794-306ed713-3d96-4984-9251-3b1558cc47e5.png)

**Comment by pschatzmann** [comment]
Do you hear a tone when you run the webserver sine generator test sketch ?

**Comment by aqildad-create** [comment]
No  didn't run webserver sine generator test ,  i am searching this sketch in your examples ,

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-webserver/streams-generator-webserver_wav

**Comment by aqildad-create** [comment]
Yes , i am hearing the tone of sine generator test sketch .

**Comment by pschatzmann** [comment]
What is your input device ? Do you get a valid signal on both channels ?

**Comment by aqildad-create** [comment]
device : INMP441
Do you get a valid signal on both channels ? I just run i2s plotter and  am getting proper wave form .
I am removing the converter and update the result .

![image](https://user-images.githubusercontent.com/65456998/225714682-2b267f2d-c567-4594-ab97-1dd309f8b4ce.png)

**Comment by pschatzmann** [comment]
If you use this microphone with 16 bits you most likely get one clean channel and one with noise!
That's the reason for my converter. Alternatively you can just use 32 bit instead of 16. 24 bits might work as well when you have a recent version of my library...

**Comment by aqildad-create** [comment]
yes sir , its working @ 32 bits per sample .  Thank you sir .
