### ISSUE TITLE
No TDM mode example

### ISSUE THREAD

**Issue by Raduq91** [pschatzmann/arduino-audio-tools#698]
Does it support TDM? do you want to make an example? I see "TDM" mentioned here: src/AudioI2S/I2SESP32-New.h; src/AudioI2S/I2SConfig.h
I want to try to connect alc883

![t1](https://user-images.githubusercontent.com/31180871/226514208-6e2fc59f-53bd-4c3d-bc90-d788fc0b811c.png)
![t2](https://user-images.githubusercontent.com/31180871/226514220-6ca20f09-699d-4ed1-817f-1cc9473a7378.png)

datasheet:
[alc883.pdf](https://github.com/pschatzmann/arduino-audio-tools/files/11024896/alc883.pdf)

**Comment by pschatzmann** [comment]
No, I did not implement TDM yet (also because I have no way to test this), but feel free to uncomment and extend the logic.
Please be aware that this is only available with IDF 5.0, so it is not available in Arduino yet.
