### ISSUE TITLE
Error compiling base-file_mp3-a2dp

### ISSUE THREAD

**Issue by rrezaei2** [pschatzmann/arduino-audio-tools#7]
Hello,

By compiling, I get following error:
T result= 0;
Buffers.h Error: conversion from 'int' to Non-scalar type 'channels' requested.

My Target is to send and play some Sound file, e.g. as mp3 using esp32 Bluetooth and a headset.

Regards,
Reza

**Comment by pschatzmann** [comment]
for which example did you get the error ?

**Comment by rrezaei2** [comment]
Base-file_mp3-a2dp

**Comment by pschatzmann** [comment]
Very strange, I tried to reproduce your issue but I don't get any errors:

- Can you check that you have the latest version of the libraries and example
- ->Arduino -> Preferences -> Compiler Warnings is at Default
- Checking in the Board Manager: ESP32 I am using the latest version which is 1.0.6
