### ISSUE TITLE
esp266 - spiffs-mp3-i2s error

### ISSUE THREAD

**Issue by aqildad-create** [pschatzmann/arduino-audio-tools#701]
upload mp3 file via esp266 sketch data upload.

 I want to play mp3-i2s but getting below exception , 

[I] AudioEncoded.h : 249 - virtual void audio_tools::EncodedAudioPrint::setNotifyAudioChange(audio_tools::AudioBaseInfoDependent&)

User exception (panic/abort/assert)
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Unhandled C++ exception: OOM

>>>stack>>>

ctx: cont
sp: 3ffffe40 end: 3fffffc0 offset: 0000
3ffffe40:  3fff726c 00001b20 00000020 40100b14  
3ffffe50:  000000fe 00000000 00000000 00000000  
3ffffe60:  00000000 00000000 00000000 00000001  
3ffffe70:  00007fff 00000000 3fff259c 3fff26e8  
3ffffe80:  3fff20f8 40207f8b 00002800 4020eade  
3ffffe90:  3fff20f8 40207f8b 00000020 4020eafd  
3ffffea0:  4020c194 3ffe8eb8 00002800 4020d6f0  
3ffffeb0:  3fff20f8 3fff2160 3fff350c 40207f8b  
3ffffec0:  3ffe8f83 00000001 3fff34e4 3fff26e8  
3ffffed0:  3fff20f8 3fff2160 3fff34e4 402082da  
3ffffee0:  3fff20f8 3fff2160 3fff2160 40208f9c  
3ffffef0:  3fff20f8 3fff2160 3fff259c 4020a975  
3fffff00:  40218b58 0000ac44 00000002 00000010  
3fffff10:  00000001 00000001 00000000 00000002  
3fffff20:  0000000f 00000003 00000000 00000000  
3fffff30:  40218b58 0000ac44 00000002 00000010  
3fffff40:  00000001 00000001 00000000 00000002  
3fffff50:  0000000f 00000003 00000000 00000000  
3fffff60:  40218b58 0000ac44 00000002 00000010  
3fffff70:  00000001 00160001 00000000 00000002  
3fffff80:  0000000f 00000003 00000000 00000000  
3fffff90:  00000000 feefeffe feefeffe 3fff26e8  
3fffffa0:  3fffdad0 00000000 3fff26d4 4020e3a0  
3fffffb0:  feefeffe feefeffe 3ffe8874 40100d9d  
<<<stack<<<

last failed alloc call: 40207F8B(10240)

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

last failed alloc caller: 0x40207f8b

![image](https://user-images.githubusercontent.com/65456998/226702464-e4666fe2-8082-499e-b7ea-a92863f822e5.png)

**Comment by pschatzmann** [comment]
Seems that there is not enough memory. I suggest that you switch to an ESP32 which has more RAM
