### ISSUE TITLE
How to Config Play mp3 via DAC from Stereo to Mono.

### ISSUE THREAD

**Issue by Rkramkhirin** [pschatzmann/arduino-audio-tools#707]
Hello, 
 I used example "streams-memory_mp3-analog" with ESP32 it is stereo, but it has a lot of noise. 
 So, I think if I change it to be mono maybe it can fix the result about noise problem. 
 Please suggest about how to config from stereo to mono (GPIO 26).
I try to change this config in the "AudioConfig.h " about DEFAULT_CHANNELS = 1 but it still stereo.

#ifndef DEFAULT_CHANNELS 
#define DEFAULT_CHANNELS 1 // Default 2
#endif

this is my code config.

  AnalogAudioStream Analog_Stream;
  EncodedAudioStream DAC_out(&Analog_Stream, new MP3DecoderHelix());
  AudioLogger::instance().begin(Serial, AudioLogger::Info);
  auto cfg = Analog_Stream.defaultConfig();
  cfg.channels = 1;
  Analog_Stream.begin(cfg);
  DAC_out.begin();

Thanks

**Comment by pschatzmann** [comment]
The noise in the DAC most likely comes from a noisy power supply. If you want to generate mono you will need to record the mp3 in mono or transform the stereo with a channel converter.

However the "best way" to resolve this is to use an external DAC!
