### ISSUE TITLE
streams-i2s-webserver_wav.ino Static IP Address

### ISSUE THREAD

**Issue by shri360** [pschatzmann/arduino-audio-tools#747]
Hello!

i want to give static IP address "192.168.4.80" for server instead of "192.168.4.1".

Where i need to modify in the Program? I need your support.

Thank you.

**Comment by pschatzmann** [comment]
Why do you think that anything needs to be changed ? 
Just set up the Wifi in the setup before you use the webserver...

**Comment by shri360** [comment]
Thank you for your response.

I'm making one setup, so server should have static ip.

yeah, as you told just defined Wi-Fi for static Ip in the setup. it's working flawlessly.

Thank you.
