### ISSUE TITLE
Not all Http stream are played

### ISSUE THREAD

**Issue by FatherMarco1971** [pschatzmann/arduino-audio-tools#753]
"http://ice07.fluidstream.net:8080/KissKiss.mp3"

the sample player_url_icy_audiokit remain stucked waiting data on the upper link.
The link work perfectly with chrome or VLC.

Could be an error in the url management in the arduino-audio-tool?
I suspect the problem is with link require to use a PORT (8080 in this case) since the problem seems to be in link with explicit port (Another sample "https://s4.yesstreaming.net:17199/stream" same behaviour), i tried to debug but I can't find the problem...

**Comment by pschatzmann** [comment]
You can set the log level to debug to verify what's happening...

**Comment by pschatzmann** [comment]
We loop until in.available() returns any data!
As far as I can see the issue is not with the Arduino code, but the fact that the service does not return any data!

**Comment by FatherMarco1971** [comment]
What do you mean with service?
I tried all to find the right "available()" method without succes.
I tought it was the ICYstream.h one but it wasn't....
I added a log in all avialable() method in your code without success.
THe only thing i can think is that it si outside from your library? Where then?

**Comment by pschatzmann** [comment]
Try to open the link in a REST tool like 

- Advanced REST Client,
- Postman

There you should be able to reproduce that you don't receive any data.

**Comment by FatherMarco1971** [comment]
Well you are right. I've not understand why it doesn't work  but it don't seems a problem of arduino code.
It seems the server won't provide answer.

**Comment by pschatzmann** [comment]
Did you try by providing a User-Agent from a know browser ? Chrome e.g. is sending Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
