### ISSUE TITLE
Please add some information to the pcm5102 breakout board description

### ISSUE THREAD

**Issue by haecksenwerk** [pschatzmann/arduino-audio-tools#773]
First of all, thanks for this great library. I had a lot of fun making a little internet radio with it :) 

The [pcm5102 DAC module](https://github.com/pschatzmann/arduino-audio-tools/wiki/External-DAC#hiletgo-pcm5102-i2s-iis-lossless-digital-audio-dac-decoder) did not work for me right away. I had to add solder bridges on the bottom side. The bridges H1-H4 are connected to the not assembled pin header. The mapping is as follows:

H1L (FLT) = L
H2L (DMP) = L
H3L (XMT) = H
H4L (FMT) = L  (most important, sets the audio format to I2S)

![IMG_0408](https://user-images.githubusercontent.com/77981303/232213355-93542f42-e6ee-4e16-add7-15a7b20fc30b.jpeg)

**Comment by pschatzmann** [comment]
Did you try to change the i2s format in the configuration ?

**Comment by haecksenwerk** [comment]
@pschatzmann No, I wasn't aware of that option

**Comment by pschatzmann** [comment]
I updated the documentation. It seems that the DACs from Adafruit are also not using standard I2S...
