### ISSUE TITLE
setDeboundDelay() a typo in AudioActions.h??

### ISSUE THREAD

**Issue by Gaai** [pschatzmann/arduino-audio-tools#778]
Probably a typo or was this intended? Description says debouceDelay...

**Comment by pschatzmann** [comment]
yes, that's wrong. Will you submit a pull request ?

**Comment by Gaai** [comment]
Never done that, but I'll see what I can do tomorrow. Got to learn that anyway. Should be a simple enough start ;)
Thanks for your awesome work btw. Only just started to read through all the files and I already see endless possibilities made available with few lines of code by end user. See what I can do to support.

**Comment by Gaai** [comment]
Done
