### ISSUE TITLE
merging multiple mp3 file sources from sd to i2s

### ISSUE THREAD

**Issue by drfhaust** [pschatzmann/arduino-audio-tools#780]
Hello there! I must commend you on your excellent library. I am currently developing a solution that involves combining up to five MP3 files into a single output for I2S. Could you please provide some assistance with this?

**Comment by pschatzmann** [comment]
On a desktop you might be able to do this. On a microcontroller there is just not enough memory and cpu speed to do this!
The issue is MP3!

If you switch to wav, this should be possible however...

**Comment by pschatzmann** [comment]
ps. there are discussions for these type of questions...
