### ISSUE TITLE
Two I2S outputs with a delay effect on one of them - help needed

### ISSUE THREAD

**Issue by MohammedSamy** [pschatzmann/arduino-audio-tools#781]
Hello,

Please would appreicate some help on this topic. I am trying to do a project where I read from an I2S input and then forward the data to two I2s outputs at the same time, but one of them will have a delay effect on it (max should be 1500ms delay). I am using an ESP32 and your amazing library (super kudos by the way).

First, I am trying to takle the delay probelm by just sending the same data to the two I2S channels but one with delay. I tried multple things, but I cannot get an effect to work on only one of them. So then I tried to make sure that the two I2S outputs are separate from each other, but no avail. I followed the example I2s-I2s-2 but the problem is:

- If I set the I2s.port_no config to be 0 on one of the I2s and the other to set as 1, and I also set both configs as master then only one of the I2s ouputs would work.
- If I do not set the I2s.port_no config or leave them default as 0, then the output works on both but it is the same output and the effect that I put on one of them does not work. I am sure because when I comment out the copier for the 2nd output the two I2s outputs still work which is strange. The library sees two I2s outputs configured and they have the same port_no so it automatically sets the data to both outputs even though I am not copying into the second I2s output.

So the solution should be that I utilize the port_no config to be different, but then as mentioned only one output works.  I am guessing from the description is that in this case where I have two different port_no than I need to assign the copy to a different core in the ESP32,, is this the case? how can I do that.

I attached here the code where I have different port_no configured but only one I2s output works. could you please help? thank you in advance!
```

/**
 * @file streams-url_mp3-i2s.ino
 * @author Phil Schatzmann
 * @brief decode MP3 stream from url and output it on I2S
 * @version 0.1
 * @date 2021-96-25
 * 
 * @copyright Copyright (c) 2021
 */

// install https://github.com/pschatzmann/arduino-libhelix.git

#include "AudioTools.h"
#include "AudioCodecs/CodecMP3Helix.h"


I2SStream i2s; // final output of decoded stream
I2SStream i2sStream1;
MP3DecoderHelix helix;
EncodedAudioStream dec(&i2s, &helix); // Decoding stream
EncodedAudioStream dec1(&i2sStream1, &helix); // Decoding stream
StreamCopy copier(dec, url); // copy url to decoder
StreamCopy copier1(dec1, url); // copy url to decoder


void setup(){
  Serial.begin(115200);
  AudioLogger::instance().begin(Serial, AudioLogger::Info);  


  // setup i2s
  auto cfg = i2s.defaultConfig(TX_MODE);
  cfg.i2s_format = I2S_STD_FORMAT; // if quality is bad change to I2S_LSB_FORMAT https://github.com/pschatzmann/arduino-audio-tools/issues/23
 // cfg.sample_rate = 44100;
  cfg.channels = 2;
  cfg.bits_per_sample = 16;
    cfg.i2s_format = I2S_STD_FORMAT;
  cfg.pin_bck = PIN_I2S_BCK;
  cfg.pin_ws = PIN_I2S_WS;
 // cfg.pin_data_rx = PIN_I2S_DATA_IN;
  cfg.pin_data = 18;
  cfg.is_master = true;
  cfg.port_no = 0;
  i2s.begin(cfg);



 Serial.println("starting I2S...");
  auto config1 = i2sStream1.defaultConfig(TX_MODE);
  config1.i2s_format = I2S_STD_FORMAT; // if quality is bad change to I2S_LSB_FORMAT https://github.com/pschatzmann/arduino-audio-tools/issues/23
  //config1.sample_rate = 44100;
  config1.channels = 2;
 config1.bits_per_sample = 16;
    config1.i2s_format = I2S_STD_FORMAT;
  config1.pin_bck = 16;
  config1.pin_ws = 17;
  //config1.pin_data_rx = PIN_I2S_DATA_IN;
  config1.pin_data = 5;
  config1.port_no = 1;
    config1.is_master = true;
  i2sStream1.begin(config1);
  Serial.println("I2S started");


helix.begin();
  // setup I2S based on sampling rate provided by decoder
  dec.setNotifyAudioChange(i2s);
  dec.begin();
  dec1.setNotifyAudioChange(i2sStream1);
  dec1.begin();
// mp3 radio
  url.begin("http://stream.srg-ssr.ch/m/rsj/mp3_128","audio/mp3");

}

void loop(){
  copier.copy();
    copier1.copy();
}

```

**Comment by pschatzmann** [comment]
I would suggest the following solution:
- Leave the 2 I2S streams: one on port 0 and the other on port 1
- Add them to a MultiOutput
- Send the output from EncodedAudioStream to the MultiOutput
- Remove the second EncodedAudioStream and StreamCopy
- Optional: I would expect that the time delay will not be audible, but you can try to decrease the copy size by adding the parameter to the constructor and/or you can increase the i2s buffer size of the first output by the copy size to add a very small delay.
