### ISSUE TITLE
Base-adc-a2dp not working. fault: 'Frame' was not declared in this scope

### ISSUE THREAD

**Issue by Bollebie** [pschatzmann/arduino-audio-tools#79]
i have installed latest version of arduino-audio-tools.
when testing Base-adc-a2dp sketch i get fault: 'Frame' was not declared in this scope

**Comment by pschatzmann** [comment]
You need upgrade the A2DP library as well...

**Comment by Bollebie** [comment]
thanks, i've tested with latest A2DP library and the sketch compiled with no errors.
