### ISSUE TITLE
Reverb classes are missing required implementations of pure virtual methods

### ISSUE THREAD

**Issue by KSpotter** [pschatzmann/arduino-audio-tools#803]
The four reverb classes (STKFreeVerb, STKChowningReverb, STKNReverb, and STKPerryReverb) are missing required implementations of pure virtual methods.

An attached copy of "src/AudioLabs/AudioSTK.h" was modified to include the missing method definitions in all four reverb classes.

Also attached is "streams-audiokit-reverb-audiokit.ino", which provides an example of using each of the four reverb classes. The comments in the example provide helpful tips about sampling rate and buffer size to improve the responsiveness of the reverbs.

The modified source file and example code were tested on an ESP32-Audio-Kit with ES8388 (i.e., board configuration 5).

[AudioSTK.h.txt](https://github.com/pschatzmann/arduino-audio-tools/files/11315060/AudioSTK.h.txt)
[streams-audiokit-reverb-audiokit.ino.txt](https://github.com/pschatzmann/arduino-audio-tools/files/11315064/streams-audiokit-reverb-audiokit.ino.txt)

**Comment by pschatzmann** [comment]
Please submit a pull request!
