### ISSUE TITLE
Allocation of OutputMixer object and OutputMixer.setOutputStream()

### ISSUE THREAD

**Issue by leelx78** [pschatzmann/arduino-audio-tools#829]
Hi @pschatzmann just a minor thing. I needed to allocate an OutputMixer object inside another class but I noticed there is no constructor without arguments, nor a way to set the output stream so I added it as below: 

```
 class OutputMixer : public Print {
 
  public:
  OutputMixer(){

  };
  void setOutputStream(Print &finalOutput){
    p_final_output = &finalOutput;
  }

  <the rest is unchanged>
  ``` 
  
  Can this be added to the code? Might give more flexibility since we can configure and reconfigure the mixer later after creation.
  
  Thanks!

**Comment by pschatzmann** [comment]
Sur, just submit a pull request with your change

**Comment by pschatzmann** [comment]
What's holding you up ? Can I still expect your contribution ?

**Comment by leelx78** [comment]
Sorry @pschatzmann I'm not familiar with pull requests so I left it there for the time being. 

Are you pasting it from there? I'm fine with both setOutputStream() and setOutput() names.

Thanks

**Comment by pschatzmann** [comment]
I just committed some new functionality!
Pull requests are not too difficult, you would need to fork this project first and then you can make your changes in your fork.
