### ISSUE TITLE
 cannot declare variable 'music' to be of abstract type 'audio_tools::MemoryStream'

### ISSUE THREAD

**Issue by riraosan** [pschatzmann/arduino-audio-tools#84]
Hi. pschatzmann

IDE:PlatfromIO 
arduino-esp32: 1.0.6
arduino-audio-tool: v0.8

I detected a compile error when I was building streams-memory_raw-i2s sample code.

src\main.cpp:9:14: error: cannot declare variable 'music' to be of abstract type 'audio_tools::MemoryStream'
 MemoryStream music(StarWars30_raw, StarWars30_raw_len);

I modified AudioStreams.h.

151
```c++
  virtual size_t readBytes(char *buffer, size_t length) {
    size_t count = 0;
    while (count < length) {
      int c = read();
      if (c < 0) break;
      *buffer++ = (char)c;
      count++;
    }
    return count;
  }

  virtual size_t readBytes(uint8_t *buffer, size_t length) {
    size_t count = 0;
    while (count < length) {
      int c = read();
      if (c < 0) break;
      *buffer++ = (char)c;
      count++;
    }
    return count;
  }
```

You can fix it if you like.👍

**Comment by pschatzmann** [comment]
Thanks for letting me know. 

I am about to make the library available for RP2040 processors and needed to change the class hierarchy. Unfortunately I haven't tested all examples yet.

My correction has been committed to Github.
