### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by AlixANNERAUD** [pschatzmann/arduino-audio-tools#860]
I get the following error when I try to compile :
```
.pio/libdeps/wt32-sc01-plus/audio-tools/src/AudioCodecs/CodecADPCM.h:2:10: fatal error: ADPCM.h: No such file or directory
```
This is due to the new codec is `ADPCM` which is now included in`CodecWAV.h`. It has to be made optional in some way (or copy directly it in the repo as a submodule for example).

**Comment by pschatzmann** [comment]
I refactored the class a bit to remove the dependency
