### ISSUE TITLE
Publish this repository to Platform IO registry

### ISSUE THREAD

**Issue by AlixANNERAUD** [pschatzmann/arduino-audio-tools#861]
It would be great to add this repository directly to Platform IO  registry since it seems to be mature enough (https://docs.platformio.org/en/latest/librarymanager/creating.html).

**Comment by pschatzmann** [comment]
My current decision is not to publish this library in the Arduino Library Manager or in the Platform IO registry.

I want to avoid to attract beginners that have no clue what they are doing. After all, I was getting some negative feed-back that this library is too complicated.

However, this might change in the future...

**Comment by ncmreynolds** [comment]
Hi there Phil would you reconsider publishing in the Arduino library manager? It's a really powerful library and doing so should make it more discoverable. A big advantage to end users would be notification of version changes and simple auto updating from within the IDE.
