### ISSUE TITLE
How to get volume setting ?

### ISSUE THREAD

**Issue by AlixANNERAUD** [pschatzmann/arduino-audio-tools#883]
When I try to get the current volume setting of a `VolumeStream` (using `volume()` or `volume(channel)` methods), I always get 0, even if I set the volume before (using `setVolume()`). From what I have seen in these methods definitions, `setVolume` set `factor_for_channel` attribute, but `volume` get the volume from `volume_values`. I understand why these attributes are separated, but I don't get why `setVolume` doesn't set `volume_values` also. Maybe I have misunderstood something ?

**Comment by pschatzmann** [comment]
Looks like a bug: I just committed a correction!

**Comment by AlixANNERAUD** [comment]
Ok, thank you !
