### ISSUE TITLE
Issue with `pin_mck` on ESP32.

### ISSUE THREAD

**Issue by AlixANNERAUD** [pschatzmann/arduino-audio-tools#886]
In commit 69a0e5a, you removed the default value of -1 for `pin_mck`. I don't know if it's a problem on regular ESP32 board, but on the WT32-SC01 Plus, it's disturbing the driving of the LCD display :
![Capture d’écran du 2023-06-04 15-53-01](https://github.com/pschatzmann/arduino-audio-tools/assets/44531068/b3bfa7cf-4648-4cd1-8d83-982a82c92229)

Since this pin is not required for operation, why not left it in disabled mode by default (-1) ?

**Comment by pschatzmann** [comment]
This has been introduced to support the AudioKit. 
I just committed a correction which makes sure that the mck pin is only setup for this case.
