### ISSUE TITLE
Various issues with File / FileLoop on Desktop

### ISSUE THREAD

**Issue by shlomozippel** [pschatzmann/arduino-audio-tools#887]
I'm trying to test everything on Desktop and running into issues:

1. The File implementation in `AudioLibs/Desktop/File.h` can't be trivially copied, which FileLoop does in `setFile()`. The error is `error: call to implicitly-deleted copy constructor of 'audio_tools::File'`
2. FileLoop.h tries including `FS.h` which doesn't exist in Desktop. Instead it should include `AudioLibs/Desktop/File.h`

**Comment by pschatzmann** [comment]
Don't expect all the functionality of  AudioLibs to work on the desktop. This is only guaranteed for the basic functionality.
I committed some corrections, so that there are no compile errors for that scenario...
