### ISSUE TITLE
ESP32 I2S audio in and analog audio out

### ISSUE THREAD

**Issue by Lukmicsch** [pschatzmann/arduino-audio-tools#894]
Firstly, thank you very much for such a great library.

Setup: ESP32 DEVKIT V1, INMP441 (GPIO32, GPIO15, GPIO14), LM386 (GPIO25)

I can successfully run "I2S to Webserver" and "Streaming Radio Player", but as soon as I want to combine these two approaches I get into trouble.

Example with "I2S to Webserver" sketch:
I leave the sketch as is and start adding the components for the analog output:

```
#include "AudioCodecs/CodecMP3Helix.h"
URLStream url("","");
AnalogAudioStream analog; // final output of decoded stream
EncodedAudioStream dec(&analog, new MP3DecoderHelix()); // Decoding stream
StreamCopy copier(dec, url); // copy url to decoder
```
and then I add to the setup:
```
void setup() {
  Serial.begin(115200);
  AudioLogger::instance().begin(Serial, AudioLogger::Info);

  // RECEIVER SETUP
  Serial.println("starting Analog...");
  auto config_rec = analog.defaultConfig(TX_MODE);
  analog.begin(config_rec);
  ...
}
```
As soon as I add `analog.begin(config_rec);` the audio stream does not work anymore and the monitor shows:
```
E (15971) I2S: /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/driver/i2s.c:1352 (i2s_read):rx NULL
[E] I2SESP32.h : 103 - size_t audio_tools::I2SDriverESP32::readBytes(void*, size_t)
[I] StreamCopy.h : 139 - StreamCopy::copy 1024 -> 0 -> 0 bytes - in 0 hops
```
I don't understand why this wouldn't work, as everything works on its own and they should not have conflicts as one is analog and the other is I2S.

What am I doing wrong?

**Comment by pschatzmann** [comment]
You must make sure that you use different ports: note Analog output or input must always be on port 0
