### ISSUE TITLE
Compilation error when running streams-generator-serial.ino

### ISSUE THREAD

**Issue by rockalterngear** [pschatzmann/arduino-audio-tools#916]
I tried to run the streams-generator-serial.ino example from the library with no changes made and I got a compilation error that had the following error message:
[error_message.txt](https://github.com/pschatzmann/arduino-audio-tools/files/11988493/error_message.txt)

After making a quick search on the latest commits I found that the latest commit that didn't gave me the compilation error was:  https://github.com/pschatzmann/arduino-audio-tools/commit/2174cecef7f0341d32e5ebbe30919e8cd6e7758f
So the bug was introduced on:
https://github.com/pschatzmann/arduino-audio-tools/commit/6a103da4a931524da9c8cfc9829b8af55f3e2cc4

The problem seems to be on the src/AudioTools/AudioType.h file, specifically on the line 34:
![image](https://github.com/pschatzmann/arduino-audio-tools/assets/107006939/f7aa267a-609b-4d86-8480-44dbcf72c3d2)
When removing the "HZ" added part, the code compiles again, however I couldn't find out why. 

The IDE version I'm currently using is: 2.1.1
Developement board I'm compiling to: Xiao ESP32C3 

By the way, thank you for the great work with this library, is being really helpful for my projects.

**Comment by pschatzmann** [comment]
Strange: the C3 seems to have added a conflicting define for HZ. 
Undefining it was resolving the issue...
