### ISSUE TITLE
Clicking Noise mp3 from SD

### ISSUE THREAD

**Issue by souza107** [pschatzmann/arduino-audio-tools#92]
Getting a clicking noise on an MP3 files in headphones ...using player-sd-audiotkit modified for Lyra 4.3. I tried just lowering volume but noise is still there any suggestions?

**Comment by pschatzmann** [comment]
What did you modify ?

**Comment by pschatzmann** [comment]
Oh - No, just read the readme of the https://github.com/pschatzmann/arduino-audiokit project

**Comment by souza107** [comment]
Thats were I started but needed to use the sdfat library and mp3. I guess I could convert to wave but couldn't figure out how to incorporate sdfat because the Lyra used different pins

**Comment by pschatzmann** [comment]
For me this was working with all dip switches in the on position.

**Comment by souza107** [comment]
ok so I used this exact file "Arduino audio tools/examples/player-sd-audiotkit" with all the dip switches up and it plays but I am still getting a clicking noise when song plays

**Comment by pschatzmann** [comment]
Did you switch the log level to Warning ?

**Comment by souza107** [comment]
I did ... Do I need to set buffer size or sample rate?

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/arduino-audio-tools/wiki/Performance

**Comment by souza107** [comment]
I tested the cable from computer to speaker and it works fine...So I don't think its the hardware. I really appreciate all the help

**Comment by souza107** [comment]
No luck...Any other suggestions?

**Comment by pschatzmann** [comment]
What is the sample rate of your files ?
Is it with all files ?
Could could try some other decoders...
Maybe you can share one of your files so that I can double check on my board...

**Comment by souza107** [comment]
libhelix -  -> invalid frame size: -1 / max: 1600

**Comment by souza107** [comment]
Sure I can share a file, rate its 44100 and I've saved it with 16bit 24 bit and 32bit float How would you like me send file

**Comment by souza107** [comment]
https://www.icloud.com/iclouddrive/0c8ZzCYC6zwdhKrJbEFbQFjqg#FireWorks2022

**Comment by souza107** [comment]
I have tried a few songs with this is the one I need to work

**Comment by souza107** [comment]
Did you get a chance to try that file out with your board? I was tinkering around all night with no success. Tried another mp3 decoder also with no luck.

**Comment by pschatzmann** [comment]
I am not sure - I am an old Vinyl guy and I tend to overhear light clicking noises as natural. 
In the example that you sent me I  think that I might hear it in the beginning - but then temporarily it goes away: My gut feeling is that might be a problem of the mp3 decoder.

**Comment by souza107** [comment]
Is there an example of playing wav or raw file from Sd?

**Comment by pschatzmann** [comment]
You can start with https://github.com/pschatzmann/arduino-audio-tools/blob/main/examples/examples-stream/streams-sd_mp3-i2s/streams-sd_mp3-i2s.ino
- for Wav just replace the decoder with WAVDecoder
- for raw just use the file as direct source

**Comment by souza107** [comment]
One last question hopefully you can help. I need to access 1 external pin for input. Do you know which one I can use while still accessing the sd and headphone out

**Comment by souza107** [comment]
Nvm used pin 0 and it works… thanks again for all help
