### ISSUE TITLE
A2DPStream needs too much program memory

### ISSUE THREAD

**Issue by framik80** [pschatzmann/arduino-audio-tools#952]
I'm trying to use the library to use the ESP32 to play different files from the SD card on a BT speaker depending on the button pressed.

My little sketch works with your May 20 library (91% program memory)
But when I used the current version, the memory is exceeded (109% program memory).

It seems that A2DPStream is too big now.

> The sketch uses 1439525 bytes (109%) of program memory. The maximum is 1310720 bytes.

**Comment by pschatzmann** [comment]
I don't understand why you file this as an issue: You obviously just fogot to set the right partition scheme

**Comment by gauravacad** [comment]
Better you set the partition scheme as No OTA (2 MB app/2 MD spiff) 
Am i right ?

**Comment by pschatzmann** [comment]
Only if you intent to use SPIFF. 
I am usually using Huge APP
