### ISSUE TITLE
WIFI and A2DP not working even USE ONE AT A TIME 

### ISSUE THREAD

**Issue by aqildad-create** [pschatzmann/arduino-audio-tools#956]
below is the minimal code which reproduce the issue in which  I just include  a2dp library  and i want to connect WIFI .

but it always fails why ?   

#include "AudioTools.h"
#include "AudioLibs/AudioA2DP.h"
#include <WiFi.h>

String ssidfromWificredentional;
String passfromWificredentional;
 

void setup() {
  // put your setup code here, to run once:
 Serial.begin(115200);
  Serial.println("\n Starting");
  ssidfromWificredentional    =    "ggg-ttttt"; 
  passfromWificredentional    =     "abc"; 

  WiFi.mode(WIFI_AP_STA);
       int status = WL_IDLE_STATUS;
 while ( status != WL_CONNECTED) {
     
    status = WiFi.begin(ssidfromWificredentional.c_str(), passfromWificredentional.c_str());
    Serial.println("  ATTEMP "); 
 
    // wait 10 seconds for connection:
    delay(10000);
  }
 Serial.println("  CONEECTED YEAH  "); 
}

void loop() {
  // put your main code here, to run repeatedly:

}

**Comment by pschatzmann** [comment]
Why don't you just activate the logging to reproduce what's going on ?
Did you try to use the 'source-changes' branch, which implements the latest changes from Espressif ?
