### ISSUE TITLE
base a2dp sink exception 

### ISSUE THREAD

**Issue by aqildad-create** [pschatzmann/arduino-audio-tools#964]
some time i get this exception ?

![image](https://github.com/pschatzmann/arduino-audio-tools/assets/65456998/14205160-e810-4850-962c-c80783738c77)

11:28:41.217 -> assert failed: host_recv_pkt_cb hci_hal_h4.c:548 (0)
11:28:41.217 -> 
11:28:41.217 -> 
11:28:41.217 -> Backtrace: 0x40083e35:0x3ffdd580 0x40094bdd:0x3ffdd5a0 0x4009b6ed:0x3ffdd5c0 0x40142a7a:0x3ffdd6f0 0x401a9206:0x3ffdd710 0x401986ca:0x3ffdd730 0x4001791d:0x3ffdd750 0x40198f51:0x3ffdd770 0x4019902e:0x3ffdd7b0 0x400188f5:0x3ffdd7e0 0x40198913:0x3ffdd820 0x4019c30d:0x3ffdd840 0x400870bc:0x3ffdd860 0x40019d11:0x3ffdd890 0x40055b4d:0x3ffdd8b0 0x40196e47:0x3ffdd8d0 0x401974b1:0x3ffdd8f0
11:28:41.217 -> 
11:28:41.217 -> 
11:28:41.217 -> 
11:28:41.217 -> 
11:28:41.217 -> ELF file SHA256: 04e7e75be9ab2c27
11:28:41.217 -> 
11:28:41.311 -> Rebooting...
11:28:41.311 -> ets Jul 29 2019 12:21:46
11:28:41.311 -> 
11:28:41.311 -> rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
11:28:41.311 -> configsip: 0, SPIWP:0xee
11:28:41.311 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
11:28:41.311 -> mode:DIO, clock div:1
11:28:41.311 -> load:0x3fff0030,len:1344
11:28:41.311 -> load:0x40078000,len:13924
11:28:41.311 -> ho 0 tail 12 room 4
11:28:41.311 -> load:0x40080400,len:3600
11:28:41.357 -> entry 0x400805f0

**Comment by pschatzmann** [comment]
As you can see in the stack-trace this has nothing to do with any functionality provided by me. 
Can you reproduce the issue with any of my tested sketches ?

Please provide the details how to reproduce the issue.
As I told you before, please to do use images in your issues.
