### ISSUE TITLE
Arduino Nano 33 BLE / Nrf52xx Support

### ISSUE THREAD

**Issue by paulhayes** [pschatzmann/arduino-audio-tools#968]
Sorry I wasn't able to identify which boards/MPU are supported by this library. I saw that there was a mention of the Nano 33 BLE and Seeed Xiao Nrf52840 Sense in the codebase however the library doesn't compile for either. 

Are there any plans to add support for these boards in the future?

**Comment by pschatzmann** [comment]
The supported functionality depends on the processor:
https://github.com/pschatzmann/arduino-audio-tools/wiki/Supported-Architectures

**Comment by paulhayes** [comment]
Thanks that was the documentation page I was looking for.
