### ISSUE TITLE
Question on FIR filters

### ISSUE THREAD

**Issue by thaaraak** [pschatzmann/arduino-audio-tools#97]
Quick question on using the FIR filters: ESP32 Devkit running at 240MHz

I have the I2S->Filter->I2S [example](https://github.com/pschatzmann/arduino-audio-tools/tree/main/examples/examples-stream/streams-i2s-filter-i2s) running. 

What I am noticing is that while the filter does work there are artifacts in the output (see the outputs below - first for the 5 taps in the example and the second for a 32 tap low pass filter I created)

![5 Taps example](https://user-images.githubusercontent.com/60319319/154114445-7bf2d867-7530-46ff-9afb-83482550cd3c.jpg)
![32 Taps](https://user-images.githubusercontent.com/60319319/154114436-41795f62-ed58-452d-be29-f6d40cfa595c.jpg)

I am assuming that the artifacts are caused by the filter convolution code taking too much time in the processing loop - is that correct? Is there anything I can tweak - I did try playing around with the core Arduino was running on which had no effect. I didn't see any way of configuring the FIR filter to process a block of data rather than a single sample at a time.

Any thoughts or suggestions?

**Comment by pschatzmann** [comment]
I suggest to lower the sampling rate. Maybe you should even start with a very low one...
2nd proposal - apply the filter to only one channel - so you can pin down the issue to the filter

**Comment by thaaraak** [comment]
I'll play around with the sample rates. Interestingly if I give it the identity taps { 1, 0, 0, 0, ..., 0, 0 } I don't see the artifacts. Perhaps there is some compiler optimization going on in that case though. I'll keep you posted on my experiments

**Comment by thaaraak** [comment]
I think I might have found the problem. In Filter.h class ConverterNChannels this code

```
size_t convert(uint8_t *src, size_t size) {
    int count = size / channels;
    T *sample = (T *)src;
```

is not correctly deriving the sample count to process and should read

```
size_t convert(uint8_t *src, size_t size) {
    int count = size / channels / sizeof(T);
    T *sample = (T *)src; 
```

I did try this locally and it removed the artifacts I was seeing

**Comment by pschatzmann** [comment]
Cool, can you submit a pull request ?

**Comment by thaaraak** [comment]
Just did - I don't collaborate much on github so please forgive if I didn't do it correctly

**Comment by pschatzmann** [comment]
Thanks for your input - please reopen the issue if you think that it is not resolved
