### ISSUE TITLE
I2S Webserver latency

### ISSUE THREAD

**Issue by datta-alaythia** [pschatzmann/arduino-audio-tools#972]
First just wanted to thank you for writing the library.

I’ve noticed a bug where when using the library on an ESP32 chip connected to two microphones via I2S using the i2s-webserver example code, the output heard on VLC lags by about 4 seconds when the sample rate is at 6400Hz.  Changing only the sample rate from 6400Hz to 8000Hz brings the lag to approximately 1 second.

**Comment by pschatzmann** [comment]
No, this is definitely not a  bug, but it is your choice! 
I suggest to read the chapter about Performance again
