### ISSUE TITLE
Help with creating an audio recorder using a max9814, esp32 and an sd card to store wav files

### ISSUE THREAD

**Issue by DentArthur1** [pschatzmann/arduino-audio-tools#973]
Hello, i would like to have some help with the said task. I'm new to using this library and couldn't make it work alone.
Thanks

**Comment by pschatzmann** [comment]
No, the fact that you ignored the instruction to use issues to report bugs only shows that you did not even bother to read the documentation.  Your topics are all covered in the documentation and there are also plenty of examples.

So this project is clearly not for you!

**Comment by sufius** [comment]
Thank you for this very useful library, but unfortunately your documentation is very very user-UN-friendly. For example when I'm trying to find out what the difference between RX_Mode and TX_Mode is, I wont find anything - just by looking at the code. So next time you are answering so much arogant maybe you should ask yourself if you could do it better too???

**Comment by pschatzmann** [comment]
This is an open source project and you are free to propose or better provide your improvement or contribution. 
Just ranting about something does not help anybody!
