### ISSUE TITLE
Problem with stream-audikit-sd_wav

### ISSUE THREAD

**Issue by BRAINDEX-PierreC** [pschatzmann/arduino-audio-tools#977]
Hello, thank you for your work, 
I'm using the stream-audikit-sd_wav exemple with a Lyrat 4.3. Once recording, there is a .wav files of ~5seconds but the signal is only 0, not even noise (top signal in picture) .

The exemple  stream-audikit-sd-audiokit work fine with .raw files (bottom signal in picture) so I don't think there is a material/configuration problem. 

![image](https://github.com/pschatzmann/arduino-audio-tools/assets/77616707/42b6d7c8-f98e-4a5a-93e8-c504cf9b901e)

I try to switch the input line but it doesn't work.

**Comment by richyxi** [comment]
Can you try changing this line?
```
auto cfg = in.defaultConfig(RXTX_MODE);
```

i faced a similar issue

**Comment by BRAINDEX-PierreC** [comment]
perfect it worked! thank you really much !

**Comment by musiq021** [comment]
Surely this is a bug. Why would RXTX be the solution?

**Comment by pschatzmann** [comment]
Today I had some time to look into this. If you check the log you can see that the wrong pin was used to read the data from.
I have committed a correction!
